import Link from 'next/link';
import Image from 'next/image';
import {
  ArrowRight, Check, Mic, Heart, Flag, Sun, ShoppingBag, GraduationCap,
  Layers, Crop, Eye, Share2, Globe, UserX, PenLine, Send,
  Quote,
} from 'lucide-react';
import { DotGrid } from '@/components/marketing/DotGrid';
import { CardMockup } from '@/components/marketing/CardMockup';
import { FAQAccordion, type FAQItem } from '@/components/marketing/FAQAccordion';
import Reveal from '@/components/marketing/Reveal';

/* ═══════════════════════════════════════════════════════
   SECTION 2 — HERO
═══════════════════════════════════════════════════════ */
function Hero() {
  return (
    <section className="relative overflow-hidden">
      {/* Mesh gradient blobs */}
      <div aria-hidden className="absolute pointer-events-none" style={{ top: '-10%', right: '-5%', width: 700, height: 600, background: 'radial-gradient(ellipse, rgba(31,77,58,0.15) 0%, transparent 70%)', filter: 'blur(100px)' }} />
      <div aria-hidden className="absolute pointer-events-none" style={{ bottom: '-10%', left: '-5%', width: 500, height: 500, background: 'radial-gradient(ellipse, rgba(232,197,126,0.12) 0%, transparent 70%)', filter: 'blur(80px)' }} />

      <div className="relative mx-auto max-w-[1200px] px-5 lg:px-10 pt-12 pb-20 lg:pt-20 lg:pb-28 grid lg:grid-cols-2 gap-12 lg:gap-8 items-center">

        {/* LEFT — copy */}
        <div className="order-2 lg:order-1">
          <div className="font-mono text-[11px] tracking-[0.18em] uppercase mb-5" style={{ color: 'rgba(31,77,58,0.8)' }}>
            Built for campaigns worth remembering
          </div>
          <h1 className="font-display font-bold text-ink leading-[0.97] tracking-[-0.035em] text-[48px] sm:text-[64px] lg:text-[76px]">
            Make every person{' '}
            <span className="text-primary">proud to be there.</span>
          </h1>
          <p className="mt-6 text-ink-soft text-[17px] lg:text-[19px] leading-[1.55] max-w-[480px]">
            One design. Every attendee gets a personalized card that feels made
            just for them — ready to share in 30 seconds.
          </p>
          <div className="mt-8 flex flex-wrap items-center gap-3">
            <Link
              href="/signup"
              className="inline-flex items-center gap-2 px-6 py-3.5 rounded-full bg-primary text-cream font-medium hover:bg-primary-dark transition-colors"
            >
              Start free <ArrowRight size={16} strokeWidth={2} />
            </Link>
            <Link
              href="/how-it-works"
              className="inline-flex items-center gap-2 px-6 py-3.5 rounded-full border text-ink font-medium hover:border-primary hover:text-primary transition-colors"
              style={{ borderColor: 'rgba(15,31,24,0.15)' }}
            >
              See how it works <ArrowRight size={16} strokeWidth={2} />
            </Link>
          </div>
          <div className="mt-7 flex flex-wrap items-center gap-x-5 gap-y-2 text-[13px] text-muted">
            {['Free for up to 50 cards', '14-day free trial on Pro', 'Cancel anytime'].map(t => (
              <span key={t} className="inline-flex items-center gap-1.5">
                <Check size={14} strokeWidth={2.5} className="text-primary" /> {t}
              </span>
            ))}
          </div>
        </div>

        {/* RIGHT — hero image */}
        <div className="order-1 lg:order-2 relative flex items-center justify-center">
          {/* Halo glow behind image */}
          <div aria-hidden className="absolute inset-0 grid place-items-center pointer-events-none">
            <div style={{ width: 420, height: 420, borderRadius: '50%', background: 'radial-gradient(circle, rgba(31,77,58,0.14), transparent 65%)', filter: 'blur(60px)' }} />
          </div>

          <Image
            src="/hero.png"
            alt="Three personalized event cards generated by Cardly — showing attendee, speaker, and supporter variations"
            width={620}
            height={520}
            priority
            className="relative w-full max-w-[540px] lg:max-w-none drop-shadow-2xl"
            style={{ filter: 'drop-shadow(0 32px 56px rgba(15,31,24,0.22))' }}
          />

          {/* Live preview pill */}
          <div className="hidden sm:flex absolute right-0 top-8 items-center gap-2 bg-surface border border-border rounded-full px-3 py-1.5 shadow-soft">
            <span className="w-1.5 h-1.5 rounded-full bg-success animate-pulse" />
            <span className="font-mono text-[10px] tracking-[0.14em] text-ink-soft uppercase">Live preview</span>
          </div>

          {/* Shared count pill */}
          <div className="hidden sm:flex absolute left-0 bottom-8 items-center gap-2 bg-surface border border-border rounded-full px-3 py-1.5 shadow-soft">
            <Share2 size={12} strokeWidth={2} className="text-primary" />
            <span className="font-mono text-[10px] tracking-[0.14em] text-ink-soft uppercase">247 shared today</span>
          </div>
        </div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════
   SECTION 3 — SOCIAL PROOF
═══════════════════════════════════════════════════════ */
const ORGS = [
  { mono: 'AU',   name: 'African Union' },
  { mono: 'UNDP', name: 'UNDP' },
  { mono: 'MTN',  name: 'MTN Group' },
  { mono: 'GIZ',  name: 'GIZ' },
  { mono: 'PSK',  name: 'Paystack' },
  { mono: 'AFD',  name: 'Afro Future' },
];

function SocialProof() {
  return (
    <section className="border-y border-border" style={{ background: 'rgba(250,246,238,0.4)' }}>
      <div className="mx-auto max-w-[1200px] px-5 lg:px-10 py-10">
        <div className="text-center font-mono text-[10px] tracking-[0.22em] text-muted uppercase mb-7">
          Used for campaigns by
        </div>
        <div className="flex flex-wrap items-center justify-center gap-x-10 gap-y-6 text-ink-soft">
          {ORGS.map((o, i) => (
            <div
              key={o.mono}
              className={`flex items-center gap-2.5 ${i >= 3 ? 'hidden sm:flex' : ''}`}
              style={{ opacity: 0.7 }}
            >
              <span
                className="w-8 h-8 rounded-full grid place-items-center font-mono text-[10px] tracking-[0.08em] font-semibold"
                style={{ border: '1px solid rgba(58,74,66,0.3)' }}
              >
                {o.mono}
              </span>
              <span className="font-display font-semibold text-[15px] tracking-tight">{o.name}</span>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════
   SECTION 4 — THE PROBLEM
═══════════════════════════════════════════════════════ */
const CHAOS_POSTS = [
  { tag: 'branding chaos', color: '#B8423C', initials: 'JM', caption: 'guys come thru',         text: 'pan african YOUTH forum' },
  { tag: 'wrong colors',   color: '#C9A45E', initials: 'FK', caption: "see u all there!!",       text: "I'M GOING!!" },
  { tag: 'low quality',    color: '#6B7A72', initials: 'TO', caption: '📢📢📢',                  text: 'youth forum 2025' },
  { tag: 'off-brand',      color: '#3A4A42', initials: 'RA', caption: 'we outside',              text: 'djibouti vibes' },
];

function Problem() {
  const angles = [-3, 2, -1.5, 2.5];
  return (
    <section className="relative">
      <div className="mx-auto max-w-[1200px] px-5 lg:px-10 py-20 lg:py-28">
        <div className="max-w-[720px] mx-auto text-center">
          <div className="font-mono text-[11px] tracking-[0.22em] uppercase mb-5" style={{ color: 'rgba(184,66,60,0.9)' }}>
            The problem
          </div>
          <h2 className="font-display font-bold text-ink text-[38px] sm:text-[50px] lg:text-[60px] leading-[1.0] tracking-[-0.035em]">
            You need every attendee to share.{' '}
            <span className="text-ink-soft">They never do.</span>
          </h2>
          <p className="mt-6 text-ink-soft text-[17px] lg:text-[18px] leading-[1.6]">
            You spend months planning a campaign. You design beautiful brand assets.
            Then the day comes — and your attendees post about it however they want,
            if they post at all. The &ldquo;social media kit&rdquo; you sent in WhatsApp? Half-opened, mostly ignored.
          </p>
        </div>

        <div className="mt-14 grid grid-cols-2 lg:grid-cols-4 gap-4 max-w-[1000px] mx-auto">
          {CHAOS_POSTS.map((p, i) => (
            <div
              key={i}
              className="relative bg-surface border border-border rounded-2xl p-4 shadow-soft"
              style={{ transform: `rotate(${angles[i]}deg)` }}
            >
              <div className="flex items-center gap-2 mb-3">
                <div
                  className="w-8 h-8 rounded-full grid place-items-center text-cream font-display text-[11px] font-semibold"
                  style={{ background: p.color }}
                >
                  {p.initials}
                </div>
                <div className="font-display text-[13px] font-semibold text-ink">@user_{i + 12}</div>
              </div>
              <div
                className="aspect-square rounded-lg mb-3 relative overflow-hidden"
                style={{ background: `linear-gradient(${[120,40,200,310][i]}deg, ${p.color}, ${p.color}aa)` }}
              >
                <div
                  className="absolute inset-2 border-2 border-dashed rounded-md grid place-items-center"
                  style={{ borderColor: 'rgba(250,246,238,0.4)' }}
                >
                  <span className="font-display text-cream text-[14px] sm:text-[18px] font-bold tracking-tight text-center px-2 leading-tight opacity-80">
                    {p.text}
                  </span>
                </div>
                <span
                  className="absolute top-1.5 right-1.5 font-mono text-[9px] tracking-[0.16em] uppercase px-1.5 py-0.5 rounded text-cream"
                  style={{ background: 'rgba(15,31,24,0.55)' }}
                >
                  {p.tag}
                </span>
              </div>
              <div className="text-[12px] text-ink-soft truncate">{p.caption}</div>
            </div>
          ))}
        </div>

        <div className="mt-8 text-center font-mono text-[11px] tracking-[0.18em] text-muted uppercase">
          → Four supporters. Four different brands.
        </div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════
   SECTION 5 — THE SOLUTION
═══════════════════════════════════════════════════════ */
const SOLUTION_STEPS = [
  { n: '01', icon: <PenLine size={20} strokeWidth={1.8} />, title: 'Design', body: 'Upload your campaign artwork. Mark editable zones for name, photo, role.' },
  { n: '02', icon: <Send size={20} strokeWidth={1.8} />,    title: 'Publish', body: 'One link. WhatsApp, email, or QR. No accounts. No app downloads.' },
  { n: '03', icon: <Share2 size={20} strokeWidth={1.8} />, title: 'Attendees share', body: 'Personalized card in 30 seconds. One tap to Instagram, WhatsApp, X.' },
];

function Solution() {
  return (
    <section className="relative overflow-hidden border-y border-border" style={{ background: 'rgba(232,239,235,0.3)' }}>
      <div aria-hidden className="absolute pointer-events-none" style={{ top: '20%', left: '-10%', width: 600, height: 600, background: 'radial-gradient(ellipse, rgba(31,77,58,0.08) 0%, transparent 70%)', filter: 'blur(80px)' }} />

      <div className="relative mx-auto max-w-[1200px] px-5 lg:px-10 py-20 lg:py-28 grid lg:grid-cols-[1fr_1.05fr] gap-12 lg:gap-16 items-center">
        <div>
          <div className="font-mono text-[11px] tracking-[0.22em] text-primary uppercase mb-5">The fix</div>
          <h2 className="font-display font-bold text-ink text-[36px] sm:text-[48px] lg:text-[58px] leading-[1.0] tracking-[-0.035em]">
            One design. Thousands of personalized versions.{' '}
            <span className="text-primary">Zero designer hours.</span>
          </h2>
          <p className="mt-6 text-ink-soft text-[17px] lg:text-[18px] leading-[1.6] max-w-[540px]">
            Upload your campaign design once. Mark which parts should be filled in by attendees — name, photo, role, whatever you need. Share the link. Watch your audience generate their own branded share cards in under 30 seconds.
          </p>
        </div>

        <div className="grid gap-4">
          {SOLUTION_STEPS.map((s, i) => (
            <div key={s.n} className="relative">
              <div
                className="relative bg-surface border border-border rounded-2xl p-5 sm:p-6 flex items-start gap-4 sm:gap-5 hover:border-primary/40 hover:shadow-soft transition-all"
              >
                <div className="absolute top-4 right-5 font-mono text-[10px] tracking-[0.18em] text-muted uppercase">
                  STEP {s.n}
                </div>
                <div className="w-11 h-11 sm:w-12 sm:h-12 rounded-xl grid place-items-center bg-primary-soft text-primary shrink-0">
                  {s.icon}
                </div>
                <div className="pt-0.5 pr-12">
                  <div className="font-display text-[20px] sm:text-[22px] font-semibold text-ink tracking-tight">{s.title}</div>
                  <p className="text-ink-soft text-[14px] sm:text-[15px] mt-1.5 leading-[1.55]">{s.body}</p>
                </div>
              </div>
              {i < SOLUTION_STEPS.length - 1 && (
                <div className="absolute -bottom-3 left-9 sm:left-10 z-10">
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#1F4D3A" strokeWidth="2" strokeLinecap="round">
                    <path d="M12 4v16M6 14l6 6 6-6" />
                  </svg>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════
   SECTION 6 — USE CASES GRID
═══════════════════════════════════════════════════════ */
const USE_CASE_CARDS = [
  { label: 'Conferences',            icon: <Mic size={18} strokeWidth={1.8} />,         title: 'Conference attendees and speakers',              body: 'Every speaker, sponsor, and attendee gets their own branded variant of your event card.',                        variant: 'forest' as const, org: 'AFRICA TECH FESTIVAL',      event: 'Africa Tech Festival', role: "I'M SPEAKING AT",  name: 'Kwame Mensah', initials: 'KM', title2: 'Product Engineer' },
  { label: 'NGOs',                   icon: <Heart size={18} strokeWidth={1.8} />,        title: 'Awareness and fundraising campaigns',             body: 'Your supporters announce they\'re backing your cause — branded to your campaign.',                              variant: 'cream'  as const, org: 'PAN-AFRICAN CLIMATE',       event: 'I stand for the climate.', role: "I'M SUPPORTING",  name: 'Fatou Diop',   initials: 'FD', title2: 'Supporter, Dakar' },
  { label: 'Political campaigns',    icon: <Flag size={18} strokeWidth={1.8} />,         title: 'Endorsement and rally cards',                    body: 'Volunteers, endorsers, and supporters generate cards that look professional and personal at once.',               variant: 'duotone'as const, org: 'UNITED FOR EAST AFRICA',    event: "I'm with the movement.", role: "I'M ENDORSING",   name: 'Liya Tesfaye', initials: 'LT', title2: 'Volunteer Captain' },
  { label: 'Religious organizations',icon: <Sun size={18} strokeWidth={1.8} />,          title: 'Event registration and community drives',        body: 'Members announce attendance at your conference, fast, or fundraiser.',                                           variant: 'gold'   as const, org: 'GLOBAL HALAL SUMMIT',       event: 'Global Halal Summit',  role: "I'M ATTENDING",   name: 'Yusuf Bello',  initials: 'YB', title2: 'Delegate, Kano' },
  { label: 'Brand activations',      icon: <ShoppingBag size={18} strokeWidth={1.8} />, title: 'Product launches and store openings',            body: 'Your customers and partners share branded launch announcements that drive real reach.',                           variant: 'forest' as const, org: 'MTN BRAND ACTIVATION',      event: 'MTN 5G is here.',      role: "I'M CELEBRATING", name: 'Chidinma O.',  initials: 'CO', title2: 'MTN Ambassador' },
  { label: 'Educational institutions',icon: <GraduationCap size={18} strokeWidth={1.8} />,title: 'Graduations, alumni, and scholarship campaigns',body: 'Graduates, alumni, and scholarship recipients each get their own moment to share.',                              variant: 'cream'  as const, org: 'UNIVERSITY OF NAIROBI',     event: 'Class of 2026.',       role: 'I JUST GRADUATED',name: 'Wanjiku Kariuki',initials: 'WK', title2: 'BSc Computer Science' },
];

function UseCasesGrid() {
  return (
    <section id="use-cases" className="relative">
      <div className="mx-auto max-w-[1200px] px-5 lg:px-10 py-20 lg:py-28">
        <Reveal>
          <div className="max-w-[760px] mb-12 lg:mb-16">
            <div className="font-mono text-[11px] tracking-[0.22em] text-primary uppercase mb-5">Who it&apos;s for</div>
            <h2 className="font-display font-bold text-ink text-[34px] sm:text-[44px] lg:text-[52px] leading-[1.02] tracking-[-0.03em]">
              Built for the campaign you&apos;re running this quarter.
            </h2>
            <p className="mt-5 text-ink-soft text-[17px] lg:text-[18px] leading-[1.55] max-w-[640px]">
              Six campaign types we&apos;ve shipped cards for. Your audience, your brand, in their hands.
            </p>
          </div>
        </Reveal>

        <div className="grid sm:grid-cols-2 gap-4 lg:gap-5">
          {USE_CASE_CARDS.map((c, i) => (
            <Reveal key={i} delay={i * 90}>
            <article
              className="relative bg-surface border border-border rounded-2xl p-6 lg:p-7 flex gap-5 lg:gap-6 hover:border-primary/30 hover:shadow-lift transition-all group"
            >
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2.5 mb-4">
                  <span className="w-9 h-9 rounded-full bg-primary-soft text-primary grid place-items-center shrink-0">
                    {c.icon}
                  </span>
                  <span className="font-mono text-[10px] tracking-[0.2em] text-primary uppercase">{c.label}</span>
                </div>
                <h3 className="font-display font-semibold text-ink text-[19px] lg:text-[22px] leading-[1.15] tracking-[-0.02em]">
                  {c.title}
                </h3>
                <p className="text-ink-soft text-[14px] lg:text-[15px] mt-2.5 leading-[1.55]">{c.body}</p>
                <Link
                  href="/use-cases"
                  className="mt-5 inline-flex items-center gap-1.5 text-primary font-medium text-[13px] hover:gap-2.5 transition-all"
                >
                  See example <ArrowRight size={14} strokeWidth={2} />
                </Link>
              </div>
              <div className="shrink-0 self-center hidden sm:block">
                <CardMockup
                  width={110}
                  variant={c.variant}
                  org={c.org}
                  event={c.event}
                  role={c.role}
                  name={c.name}
                  initials={c.initials}
                  title={c.title2}
                  date="2026"
                  location="AFRICA"
                />
              </div>
            </article>
            </Reveal>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════
   SECTION 7 — HOW IT WORKS (landing summary)
═══════════════════════════════════════════════════════ */
const HOW_STEPS = [
  { n: '01', title: 'Upload your design', body: 'Drop in any design from Canva, Figma, Illustrator — any PNG or JPG works. Cardly handles any aspect ratio, portrait or landscape.', caption: 'Works at any aspect ratio.' },
  { n: '02', title: 'Mark editable zones', body: 'Click to add text fields, photo zones, dropdowns, and custom fields. Different roles? Add variants — Attendee, Speaker, Sponsor.', caption: 'Each zone is one tap to edit.' },
  { n: '03', title: 'Share the link', body: 'Send one link via WhatsApp, email, or QR code. Attendees open it on their phone, type their name, upload a photo, and download in under 30 seconds.', caption: 'No app downloads. No accounts.' },
];

function HowItWorks() {
  return (
    <section id="how" className="relative">
      <DotGrid opacity={0.05} />
      <div className="relative mx-auto max-w-[1200px] px-5 lg:px-10 py-20 lg:py-28">
        <div className="max-w-[760px] mb-14 lg:mb-20">
          <div className="font-mono text-[11px] tracking-[0.22em] text-primary uppercase mb-5">How it works</div>
          <h2 className="font-display font-bold text-ink text-[34px] sm:text-[44px] lg:text-[52px] leading-[1.02] tracking-[-0.03em]">
            Three steps. About ten minutes.
          </h2>
        </div>

        <div className="space-y-16 lg:space-y-24">
          {HOW_STEPS.map((s, i) => (
            <div
              key={s.n}
              className={`grid lg:grid-cols-2 gap-10 lg:gap-16 items-center ${i % 2 === 1 ? 'lg:[&>*:first-child]:order-2' : ''}`}
            >
              <div>
                <div className="font-mono text-[10px] tracking-[0.22em] text-muted uppercase">Step {s.n}</div>
                <h3 className="mt-3 font-display font-bold text-ink text-[28px] sm:text-[34px] lg:text-[38px] leading-[1.05] tracking-[-0.02em]">
                  {s.title}
                </h3>
                <p className="mt-4 text-ink-soft text-[16px] lg:text-[17px] leading-[1.6] max-w-[520px]">{s.body}</p>
                <div className="mt-5 inline-flex items-center gap-2 font-mono text-[11px] tracking-[0.14em] uppercase text-primary">
                  <span className="w-5 h-px bg-primary" />
                  {s.caption}
                </div>
              </div>
              {/* Editor / phone visual */}
              <div
                className="relative bg-surface rounded-2xl border border-border overflow-hidden"
                style={{ boxShadow: '0 20px 60px rgba(15,31,24,0.1)', minHeight: 260 }}
              >
                <div className="h-9 bg-cream border-b border-border flex items-center gap-1.5 px-3.5">
                  {[0,1,2].map(j => <span key={j} className="w-2.5 h-2.5 rounded-full bg-ink/10" />)}
                  <div className="ml-3 font-mono text-[10px] tracking-[0.12em] text-muted">cardly.app · editor</div>
                </div>
                <div className="grid place-items-center p-8" style={{ background: 'radial-gradient(circle at center, #F1E9D6 0%, #FAF6EE 70%)', minHeight: 220 }}>
                  {i === 2 ? (
                    /* Phone mock for step 3 */
                    <div className="relative mx-auto bg-ink rounded-[28px] p-1.5" style={{ width: 160 }}>
                      <div className="rounded-[22px] overflow-hidden bg-cream" style={{ height: 280 }}>
                        <div className="h-5 bg-ink rounded-b-xl mx-auto w-16 -mt-px" />
                        <div className="px-3 pt-2 pb-3">
                          <div className="font-mono text-[7px] tracking-[0.18em] text-muted uppercase mb-1">cardly.app/y2025</div>
                          <div className="font-display text-[11px] text-ink font-semibold leading-tight mb-2">Get your card for the Youth Forum.</div>
                          <CardMockup width={130} variant="forest" org="YOUTH FORUM" event="I'm attending." role="I'M ATTENDING" name="Aisha Ahmed" initials="AA" title="Climate Lead" date="2026" location="DJI" />
                          <div className="mt-2 space-y-1.5">
                            {['Your name', 'Your role'].map(l => (
                              <div key={l} className="bg-surface border border-border rounded-md px-2 py-1.5">
                                <div className="font-mono text-[7px] tracking-[0.14em] text-muted uppercase">{l}</div>
                                <div className="text-[10px] text-ink mt-0.5">{l === 'Your name' ? 'Aisha Ahmed' : 'Climate Lead'}</div>
                              </div>
                            ))}
                            <div className="h-7 rounded-md bg-primary flex items-center justify-center mt-1">
                              <span className="font-mono text-[7px] text-cream tracking-[0.1em] uppercase">Download my card</span>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  ) : (
                    /* Editor mock for steps 1 & 2 */
                    <div className="relative">
                      <CardMockup width={150} variant="forest" org="5TH PAN-AFRICAN YOUTH FORUM" event="I'm attending." role="I'M ATTENDING" name="Aisha Ahmed" initials="AA" title="Climate Lead" date="2026" location="DJI" />
                      {i === 1 && (
                        <>
                          {[
                            { style: { top: 14, left: 10, right: 10, height: 14 }, label: 'ORG' },
                            { style: { top: 34, left: 10, right: 10, height: 24 }, label: 'EVENT' },
                            { style: { bottom: 46, left: 10, width: 30, height: 30, borderRadius: '50%' }, label: 'PHOTO' },
                            { style: { bottom: 54, left: 46, right: 10, height: 12 }, label: 'NAME' },
                          ].map(({ style, label }) => (
                            <div key={label} className="absolute" style={style}>
                              <div
                                className="absolute inset-0 border-2 border-dashed pointer-events-none"
                                style={{ borderColor: '#E8C57E', borderRadius: style.borderRadius || 4, background: 'rgba(232,197,126,0.12)' }}
                              />
                              <span className="absolute -top-3 left-0 font-mono text-[7px] tracking-[0.14em] uppercase px-1 rounded text-ink" style={{ background: '#E8C57E' }}>
                                {label}
                              </span>
                            </div>
                          ))}
                        </>
                      )}
                    </div>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-16 lg:mt-20 flex justify-center">
          <Link
            href="/how-it-works"
            className="inline-flex items-center gap-2 px-6 py-3.5 rounded-full bg-primary text-cream font-medium hover:bg-primary-dark transition-colors"
          >
            Full walkthrough <ArrowRight size={16} strokeWidth={2} />
          </Link>
        </div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════
   SECTION 8 — FEATURES (dark band)
═══════════════════════════════════════════════════════ */
const FEATURES = [
  { label: 'VARIANTS',     icon: <Layers size={20} strokeWidth={1.8} />,     title: 'One event, multiple roles',        body: 'Attendees, speakers, sponsors — each gets their own card layout from a single design.' },
  { label: 'PHOTO CROP',   icon: <Crop size={20} strokeWidth={1.8} />,       title: 'Smart photo cropping',             body: 'Matches your zone shape — circle, square, hexagon, rounded — automatically.' },
  { label: 'LIVE PREVIEW', icon: <Eye size={20} strokeWidth={1.8} />,        title: 'What they see is what they get',   body: 'Attendees see their card update as they type. No surprises at download.' },
  { label: 'SHARE BUILT-IN',icon: <Share2 size={20} strokeWidth={1.8} />,   title: 'One tap to every platform',        body: 'Instagram Stories, WhatsApp Status, X, Facebook — with caption suggestions.' },
  { label: 'AFRICA-FIRST', icon: <Globe size={20} strokeWidth={1.8} />,      title: 'Built for how Africa scrolls',     body: 'Low-bandwidth networks, mobile-first phones, WhatsApp-first sharing.' },
  { label: 'NO ACCOUNTS',  icon: <UserX size={20} strokeWidth={1.8} />,      title: 'Attendees never sign up',          body: 'They tap the link, make their card, move on. No friction. No funnel.' },
];

function Features() {
  return (
    <section className="bg-primary text-cream relative overflow-hidden">
      <div aria-hidden className="absolute inset-0 opacity-[0.06]" style={{ backgroundImage: 'radial-gradient(circle at 1px 1px, #E8C57E 1px, transparent 0)', backgroundSize: '32px 32px' }} />
      <div className="relative mx-auto max-w-[1200px] px-5 lg:px-10 py-20 lg:py-28">
        <Reveal>
          <div className="max-w-[760px] mb-12 lg:mb-16">
            <div className="font-mono text-[11px] tracking-[0.22em] text-accent uppercase mb-5">What&apos;s inside</div>
            <h2 className="font-display font-bold text-cream text-[34px] sm:text-[44px] lg:text-[52px] leading-[1.02] tracking-[-0.03em]">
              Built like a serious tool. Used like a link.
            </h2>
          </div>
        </Reveal>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-px rounded-2xl overflow-hidden border" style={{ background: 'rgba(250,246,238,0.1)', borderColor: 'rgba(250,246,238,0.15)' }}>
          {FEATURES.map((f, i) => (
            <Reveal key={i} delay={i * 80}>
            <div className="bg-primary p-6 lg:p-7 hover:bg-primary-dark transition-colors h-full">
              <div className="flex items-center gap-3 mb-5">
                <span className="w-10 h-10 rounded-lg grid place-items-center border" style={{ background: 'rgba(250,246,238,0.1)', color: '#E8C57E', borderColor: 'rgba(250,246,238,0.15)' }}>
                  {f.icon}
                </span>
                <span className="font-mono text-[10px] tracking-[0.22em] uppercase" style={{ color: '#E8C57E' }}>{f.label}</span>
              </div>
              <h3 className="font-display font-semibold text-cream text-[20px] lg:text-[22px] tracking-[-0.02em] leading-[1.15]">{f.title}</h3>
              <p className="mt-2.5 text-[14px] lg:text-[15px] leading-[1.55]" style={{ color: 'rgba(250,246,238,0.7)' }}>{f.body}</p>
            </div>
            </Reveal>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════
   SECTION 9 — PRICING TEASER
═══════════════════════════════════════════════════════ */
const PRICE_TIERS = [
  { name: 'Free',   price: '$0',  period: '',       blurb: 'For small campaigns and trials',              features: ['1 event', 'Up to 50 cards', 'Cardly watermark', 'Email support'],                                      cta: 'Start free',        href: '/signup',           primary: false },
  { name: 'Pro',    price: '$29', period: '/month', blurb: 'For most organizers',                         features: ['5 events', 'Unlimited cards', 'No watermark', '3 variants per event', 'Basic analytics'],             cta: 'Start Pro trial',   href: '/signup?plan=pro',  primary: true,  badge: 'Most popular' },
  { name: 'Studio', price: '$99', period: '/month', blurb: 'For agencies and large campaigns',            features: ['Unlimited events', 'Unlimited cards', 'Unlimited variants', 'Brand kit', 'Team accounts', 'Priority support'], cta: 'Start Studio', href: '/signup?plan=studio', primary: false },
];

function PricingTeaser() {
  return (
    <section id="pricing" className="relative">
      <DotGrid opacity={0.05} />
      <div className="relative mx-auto max-w-[1200px] px-5 lg:px-10 py-20 lg:py-28">
        <Reveal>
          <div className="max-w-[760px] mb-12 lg:mb-16">
            <div className="font-mono text-[11px] tracking-[0.22em] text-primary uppercase mb-5">Pricing</div>
            <h2 className="font-display font-bold text-ink text-[34px] sm:text-[44px] lg:text-[52px] leading-[1.02] tracking-[-0.03em]">
              Pay only when you grow.
            </h2>
            <p className="mt-5 text-ink-soft text-[17px] lg:text-[18px] leading-[1.55]">
              Start free. Upgrade when your campaign goes bigger than 50 cards.
            </p>
          </div>
        </Reveal>

        <div className="grid lg:grid-cols-3 gap-5">
          {PRICE_TIERS.map((t, i) => (
            <Reveal key={t.name} delay={i * 100}>
            <div
              className={`relative rounded-3xl p-7 lg:p-8 flex flex-col h-full ${t.primary ? 'shadow-xl' : 'border border-border'}`}
              style={t.primary
                ? { background: '#1F4D3A', color: '#FAF6EE', boxShadow: '0 20px 60px rgba(31,77,58,0.25)' }
                : { background: '#FFFFFF' }
              }
            >
              {t.badge && (
                <div className="absolute -top-3 right-7 inline-flex items-center gap-1.5 font-mono text-[10px] tracking-[0.16em] uppercase bg-accent text-primary-dark px-2.5 py-1 rounded-full font-semibold">
                  {t.badge}
                </div>
              )}
              <div className={`font-display text-[14px] font-medium tracking-tight ${t.primary ? 'text-accent' : 'text-primary'}`}>
                {t.name}
              </div>
              <div className="mt-4 flex items-baseline gap-1.5">
                <span className={`font-display font-bold tracking-[-0.03em] text-[44px] leading-none ${t.primary ? 'text-cream' : 'text-ink'}`}>
                  {t.price}
                </span>
                {t.period && <span className={`text-[14px] ${t.primary ? 'text-cream/65' : 'text-muted'}`}>{t.period}</span>}
              </div>
              <div className={`mt-1.5 text-[14px] ${t.primary ? 'text-cream/75' : 'text-ink-soft'}`}>{t.blurb}</div>

              <ul className="mt-7 space-y-3 flex-1">
                {t.features.map(f => (
                  <li key={f} className={`flex items-start gap-2.5 text-[14px] ${t.primary ? 'text-cream/90' : 'text-ink-soft'}`}>
                    <span className={t.primary ? 'text-accent' : 'text-primary'}>
                      <Check size={15} strokeWidth={2.5} />
                    </span>
                    {f}
                  </li>
                ))}
              </ul>

              <Link
                href={t.href}
                className={`mt-8 inline-flex items-center justify-center gap-2 px-5 py-3 rounded-full font-medium text-[14px] transition-colors ${
                  t.primary ? 'bg-accent text-primary-dark hover:bg-accent-dark' : 'bg-ink text-cream hover:bg-primary'
                }`}
              >
                {t.cta} <ArrowRight size={14} strokeWidth={2} />
              </Link>
            </div>
            </Reveal>
          ))}
        </div>

        <div className="mt-10 text-center">
          <Link
            href="/pricing"
            className="inline-flex items-center gap-1.5 text-primary font-medium text-[14px] hover:gap-2.5 transition-all"
          >
            See full pricing details <ArrowRight size={14} strokeWidth={2} />
          </Link>
        </div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════
   SECTION 10 — TESTIMONIAL
═══════════════════════════════════════════════════════ */
function Testimonial() {
  return (
    <section className="relative border-y border-border overflow-hidden">
      <div aria-hidden className="absolute pointer-events-none inset-0 grid place-items-center">
        <div style={{ width: 600, height: 400, background: 'radial-gradient(ellipse, rgba(31,77,58,0.07) 0%, transparent 70%)', filter: 'blur(80px)' }} />
      </div>
      <div className="relative mx-auto max-w-[860px] px-5 lg:px-10 py-20 lg:py-24 text-center">
        <div className="text-accent mx-auto mb-6 inline-flex">
          <Quote size={40} strokeWidth={1.5} style={{ fill: 'currentColor' }} />
        </div>
        <blockquote className="font-display font-medium text-ink text-[26px] sm:text-[32px] lg:text-[38px] leading-[1.2] tracking-[-0.02em] italic">
          &ldquo;Cardly let us turn 600 attendees into 600 brand ambassadors. The reach
          was far beyond what we expected — and the visual identity stayed locked the whole way.&rdquo;
        </blockquote>
        <figcaption className="mt-8 flex items-center justify-center gap-3">
          <div
            className="h-10 w-10 rounded-full shrink-0 grid place-items-center font-display font-semibold text-primary-dark text-[13px]"
            style={{ background: 'radial-gradient(120% 120% at 30% 25%, #f3e4c1 0%, #c9a45e 55%, #8a6f3a 100%)' }}
          >
            AY
          </div>
          <div className="text-left">
            <div className="text-[14px] font-semibold text-ink">Amara Yusuf</div>
            <div className="text-[12px] text-muted font-mono tracking-[0.12em] uppercase">Comms Lead · Pan-African Climate Summit</div>
          </div>
        </figcaption>
        <p className="mt-3 font-mono text-[10px] tracking-[0.18em] uppercase text-muted">[placeholder — replace with real quote]</p>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════
   SECTION 11 — FAQ
═══════════════════════════════════════════════════════ */
const LANDING_FAQS: FAQItem[] = [
  { q: 'Do attendees need to sign up?', a: 'No. Attendees never create an account. They tap your link, fill in their name, upload a photo if your card has one, and download. The whole flow takes under 30 seconds.' },
  { q: 'What file formats can I upload as my design?', a: 'PNG and JPG. Export from Canva, Figma, Illustrator, or Photoshop. Cardly works at any aspect ratio — portrait Instagram cards, landscape Twitter cards, square LinkedIn cards.' },
  { q: 'Can I have different cards for different roles?', a: 'Yes. Pro and Studio plans support variants — Attendee, Speaker, Sponsor, Volunteer. Each variant can have its own copy, badge, or layout, all generated from the same base design.' },
  { q: 'Can attendees crop their photos?', a: 'Yes. Cardly auto-crops to your zone shape (circle, square, hexagon, rounded) and lets attendees pinch-zoom and reposition before downloading.' },
  { q: 'Where can attendees share their card?', a: 'Anywhere. The download button is followed by one-tap share buttons for Instagram Stories, WhatsApp Status, X, Facebook, and LinkedIn — each with a suggested caption you can pre-write.' },
  { q: 'How is Cardly different from Canva templates?', a: 'Canva templates need every attendee to open Canva, learn the editor, find the right file, and re-save. Cardly is one link — they tap, type, download, share. Most attendees finish in under a minute.' },
  { q: 'What languages does Cardly support?', a: 'Editor UI ships in English, French, Arabic, and Swahili. The attendee form accepts any Unicode text — you can write your card prompts in any language.' },
  { q: 'Can I see analytics on who downloaded their card?', a: 'Pro and Studio plans include a dashboard with download count, share-platform breakdown, top sharers, and time-of-day patterns. No personal data is collected from attendees.' },
];

function FAQSection() {
  return (
    <section id="faq" className="relative">
      <DotGrid opacity={0.05} />
      <div className="relative mx-auto max-w-[920px] px-5 lg:px-10 py-20 lg:py-28">
        <div className="mb-10 lg:mb-14 text-center">
          <div className="font-mono text-[11px] tracking-[0.22em] text-primary uppercase mb-5">FAQ</div>
          <h2 className="font-display font-bold text-ink text-[34px] sm:text-[42px] lg:text-[48px] leading-[1.02] tracking-[-0.03em]">
            Questions we get every week.
          </h2>
        </div>
        <FAQAccordion items={LANDING_FAQS} defaultOpen={0} />
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════
   SECTION 12 — FINAL CTA
═══════════════════════════════════════════════════════ */
function FinalCTA() {
  return (
    <section className="relative overflow-hidden">
      <div aria-hidden className="absolute pointer-events-none" style={{ top: '-40%', left: '50%', transform: 'translateX(-50%)', width: 640, height: 640, borderRadius: '50%', background: 'radial-gradient(circle, rgba(232,197,126,0.22), transparent 65%)', filter: 'blur(40px)' }} />
      <DotGrid opacity={0.05} />
      <div className="relative mx-auto max-w-[920px] px-5 lg:px-10 py-24 lg:py-32 text-center">
        <h2 className="font-display font-bold text-ink text-[44px] sm:text-[58px] lg:text-[72px] leading-[0.98] tracking-[-0.035em]">
          Start your first campaign today.
        </h2>
        <p className="mt-6 text-ink-soft text-[18px] lg:text-[19px] leading-[1.55] max-w-[640px] mx-auto">
          Free for up to 50 cards. No credit card. Most users have their first card ready in under five minutes.
        </p>
        <div className="mt-9 flex flex-wrap items-center justify-center gap-3">
          <Link
            href="/signup"
            className="inline-flex items-center gap-2 px-7 py-4 rounded-full bg-primary text-cream font-medium text-[16px] hover:bg-primary-dark transition-colors"
          >
            Start free <ArrowRight size={17} strokeWidth={2} />
          </Link>
          <Link
            href="/use-cases"
            className="inline-flex items-center gap-2 text-ink underline decoration-ink/30 underline-offset-4 hover:decoration-primary hover:text-primary transition-colors text-[15px]"
          >
            See a live example <ArrowRight size={14} strokeWidth={2} />
          </Link>
        </div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════
   PAGE ASSEMBLY
═══════════════════════════════════════════════════════ */
export default function LandingPage() {
  return (
    <>
      <Hero />
      <SocialProof />
      <Reveal><Problem /></Reveal>
      <Reveal><Solution /></Reveal>
      <UseCasesGrid />
      <Reveal><HowItWorks /></Reveal>
      <Features />
      <PricingTeaser />
      <Reveal><Testimonial /></Reveal>
      <Reveal><FAQSection /></Reveal>
      <Reveal><FinalCTA /></Reveal>
    </>
  );
}
