import Link from 'next/link';
import Image from 'next/image';
import {
  ArrowRight, Check, Mic, Heart, Flag, Sun, ShoppingBag, GraduationCap,
  Layers, Crop, Eye, Share2, Globe, UserX, PenLine, Send,
  Upload, ScanLine,
} from 'lucide-react';
import { DotGrid } from '@/components/marketing/DotGrid';
import { FAQAccordion, type FAQItem } from '@/components/marketing/FAQAccordion';
import Reveal from '@/components/marketing/Reveal';
import { Testimonials } from '@/components/marketing/Testimonials';
import { StatsBar } from '@/components/marketing/StatsBar';

/* ═══════════════════════════════════════════════════════
   SECTION 2 — HERO
═══════════════════════════════════════════════════════ */
function Hero() {
  return (
    <section className="relative overflow-hidden">
      {/* Mesh gradient blobs */}
      <div aria-hidden className="absolute pointer-events-none" style={{ top: '-10%', right: '-5%', width: 700, height: 600, background: 'radial-gradient(ellipse, rgba(31,77,58,0.15) 0%, transparent 70%)', filter: 'blur(100px)' }} />
      <div aria-hidden className="absolute pointer-events-none" style={{ bottom: '-10%', left: '-5%', width: 500, height: 500, background: 'radial-gradient(ellipse, rgba(232,197,126,0.12) 0%, transparent 70%)', filter: 'blur(80px)' }} />

      <div className="relative mx-auto max-w-[1200px] px-5 lg:px-10 pt-12 pb-20 lg:pt-20 lg:pb-28 grid lg:grid-cols-[1fr_1.15fr] gap-12 lg:gap-4 items-center">

        {/* LEFT — copy */}
        <div className="order-2 lg:order-1">
          <div className="font-mono text-[11px] tracking-[0.18em] uppercase mb-5" style={{ color: 'rgba(31,77,58,0.8)' }}>
            Built for campaigns worth remembering
          </div>
          <h1 className="font-display font-bold text-ink leading-[0.97] tracking-[-0.035em] text-[48px] sm:text-[64px] lg:text-[76px]">
            Make every person{' '}
            <span className="text-primary">proud to be there.</span>
          </h1>
          <p className="mt-6 text-ink-soft text-[17px] lg:text-[19px] leading-[1.55] max-w-[480px]">
            One design. Every attendee gets a personalized card that feels made
            just for them — ready to share in 30 seconds.
          </p>
          <div className="mt-8 flex flex-wrap items-center gap-3">
            <Link
              href="/signup"
              className="inline-flex items-center gap-2 px-6 py-3.5 rounded-full bg-primary text-cream font-medium hover:bg-primary-dark transition-colors"
            >
              Start free <ArrowRight size={16} strokeWidth={2} />
            </Link>
            <Link
              href="#how"
              className="inline-flex items-center gap-2 px-6 py-3.5 rounded-full border text-ink font-medium hover:border-primary hover:text-primary transition-colors"
              style={{ borderColor: 'rgba(15,31,24,0.15)' }}
            >
              See how it works <ArrowRight size={16} strokeWidth={2} />
            </Link>
          </div>
          <div className="mt-7 flex flex-wrap items-center gap-x-5 gap-y-2 text-[13px] text-muted">
            {['Free for up to 50 cards', '14-day free trial on Pro', 'Cancel anytime'].map(t => (
              <span key={t} className="inline-flex items-center gap-1.5">
                <Check size={14} strokeWidth={2.5} className="text-primary" /> {t}
              </span>
            ))}
          </div>
        </div>

        {/* RIGHT — hero image */}
        <div className="order-1 lg:order-2 relative flex items-center justify-center lg:-mr-16">
          {/* Halo glow behind image */}
          <div aria-hidden className="absolute inset-0 grid place-items-center pointer-events-none">
            <div style={{ width: 500, height: 500, borderRadius: '50%', background: 'radial-gradient(circle, rgba(31,77,58,0.14), transparent 65%)', filter: 'blur(60px)' }} />
          </div>

          <Image
            src="/hero.png"
            alt="Three personalized event cards generated by Karta — showing attendee, speaker, and supporter variations"
            width={760}
            height={640}
            priority
            className="relative w-full"
            style={{ filter: 'drop-shadow(0 32px 56px rgba(15,31,24,0.22))' }}
          />

          {/* Live preview pill */}
          <div className="hidden sm:flex absolute right-4 top-8 items-center gap-2 bg-surface border border-border rounded-full px-3 py-1.5 shadow-soft">
            <span className="w-1.5 h-1.5 rounded-full bg-success animate-pulse" />
            <span className="font-mono text-[10px] tracking-[0.14em] text-ink-soft uppercase">Live preview</span>
          </div>

          {/* Shared count pill */}
          <div className="hidden sm:flex absolute left-4 bottom-8 items-center gap-2 bg-surface border border-border rounded-full px-3 py-1.5 shadow-soft">
            <Share2 size={12} strokeWidth={2} className="text-primary" />
            <span className="font-mono text-[10px] tracking-[0.14em] text-ink-soft uppercase">247 shared today</span>
          </div>
        </div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════
   SECTION 3 — SOCIAL PROOF
═══════════════════════════════════════════════════════ */
const ORGS = [
  { mono: 'AU',   name: 'African Union' },
  { mono: 'UNDP', name: 'UNDP' },
  { mono: 'MTN',  name: 'MTN Group' },
  { mono: 'GIZ',  name: 'GIZ' },
  { mono: 'PSK',  name: 'Paystack' },
  { mono: 'AFD',  name: 'Afro Future' },
];

function SocialProof() {
  return (
    <section className="border-y border-border" style={{ background: 'rgba(250,246,238,0.4)' }}>
      <div className="mx-auto max-w-[1200px] px-5 lg:px-10 py-10">
        <div className="text-center font-mono text-[10px] tracking-[0.22em] text-muted uppercase mb-7">
          Used for campaigns by
        </div>
        <div className="flex flex-wrap items-center justify-center gap-x-10 gap-y-6 text-ink-soft">
          {ORGS.map((o, i) => (
            <div
              key={o.mono}
              className={`flex items-center gap-2.5 ${i >= 3 ? 'hidden sm:flex' : ''}`}
              style={{ opacity: 0.7 }}
            >
              <span
                className="w-8 h-8 rounded-full grid place-items-center font-mono text-[10px] tracking-[0.08em] font-semibold"
                style={{ border: '1px solid rgba(58,74,66,0.3)' }}
              >
                {o.mono}
              </span>
              <span className="font-display font-semibold text-[15px] tracking-tight">{o.name}</span>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════
   SECTION 4 — THE PROBLEM
═══════════════════════════════════════════════════════ */
const CHAOS_IMAGES = [
  { src: '/problem-1.png', alt: 'Off-brand post — branding chaos', rotate: -3 },
  { src: '/problem-2.png', alt: 'Off-brand post — wrong colors',   rotate:  2 },
  { src: '/problem-3.png', alt: 'Off-brand post — low quality',    rotate: -1.5 },
  { src: '/problem-4.png', alt: 'Off-brand post — generic design', rotate:  2.5 },
];

function Problem() {
  return (
    <section className="relative">
      <div className="mx-auto max-w-[1200px] px-5 lg:px-10 py-20 lg:py-28">
        <div className="max-w-[720px] mx-auto text-center">
          <div className="font-mono text-[11px] tracking-[0.22em] uppercase mb-5" style={{ color: 'rgba(184,66,60,0.9)' }}>
            The problem
          </div>
          <h2 className="font-display font-bold text-ink text-[38px] sm:text-[50px] lg:text-[60px] leading-[1.0] tracking-[-0.035em]">
            You need every attendee to share.{' '}
            <span className="text-ink-soft">They never do.</span>
          </h2>
          <p className="mt-6 text-ink-soft text-[17px] lg:text-[18px] leading-[1.6]">
            You spend months planning a campaign. You design beautiful brand assets.
            Then the day comes — and your attendees post about it however they want,
            if they post at all. The &ldquo;social media kit&rdquo; you sent in WhatsApp? Half-opened, mostly ignored.
          </p>
        </div>

        <div className="mt-14 grid grid-cols-2 lg:grid-cols-4 gap-4 max-w-[1000px] mx-auto">
          {CHAOS_IMAGES.map((img, i) => (
            <div
              key={i}
              className="relative"
              style={{ transform: `rotate(${img.rotate}deg)` }}
            >
              <Image
                src={img.src}
                alt={img.alt}
                width={320}
                height={400}
                className="w-full rounded-2xl shadow-soft"
              />
            </div>
          ))}
        </div>

        <div className="mt-8 text-center font-mono text-[11px] tracking-[0.18em] text-muted uppercase">
          → Four supporters. Four different brands.
        </div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════
   SECTION 5 — THE SOLUTION
═══════════════════════════════════════════════════════ */
const SOLUTION_STEPS = [
  { n: '01', icon: <PenLine size={20} strokeWidth={1.8} />, title: 'Design', body: 'Upload your campaign artwork. Mark editable zones for name, photo, role.' },
  { n: '02', icon: <Send size={20} strokeWidth={1.8} />,    title: 'Publish', body: 'One link. WhatsApp, email, or QR. No accounts. No app downloads.' },
  { n: '03', icon: <Share2 size={20} strokeWidth={1.8} />, title: 'Attendees share', body: 'Personalized card in 30 seconds. One tap to Instagram, WhatsApp, X.' },
];

function Solution() {
  return (
    <section className="relative overflow-hidden border-y border-border" style={{ background: 'rgba(232,239,235,0.3)' }}>
      <div aria-hidden className="absolute pointer-events-none" style={{ top: '20%', left: '-10%', width: 600, height: 600, background: 'radial-gradient(ellipse, rgba(31,77,58,0.08) 0%, transparent 70%)', filter: 'blur(80px)' }} />

      <div className="relative mx-auto max-w-[1200px] px-5 lg:px-10 py-20 lg:py-28 grid lg:grid-cols-[1fr_1.05fr] gap-12 lg:gap-16 items-center">
        <div>
          <div className="font-mono text-[11px] tracking-[0.22em] text-primary uppercase mb-5">The fix</div>
          <h2 className="font-display font-bold text-ink text-[36px] sm:text-[48px] lg:text-[58px] leading-[1.0] tracking-[-0.035em]">
            One design. Thousands of personalized versions.{' '}
            <span className="text-primary">Zero designer hours.</span>
          </h2>
          <p className="mt-6 text-ink-soft text-[17px] lg:text-[18px] leading-[1.6] max-w-[540px]">
            Upload your campaign design once. Mark which parts should be filled in by attendees — name, photo, role, whatever you need. Share the link. Watch your audience generate their own branded share cards in under 30 seconds.
          </p>
        </div>

        <div className="grid gap-4">
          {SOLUTION_STEPS.map((s, i) => (
            <div key={s.n} className="relative">
              <div
                className="relative bg-surface border border-border rounded-2xl p-5 sm:p-6 flex items-start gap-4 sm:gap-5 hover:border-primary/40 hover:shadow-soft transition-all"
              >
                <div className="absolute top-4 right-5 font-mono text-[10px] tracking-[0.18em] text-muted uppercase">
                  STEP {s.n}
                </div>
                <div className="w-11 h-11 sm:w-12 sm:h-12 rounded-xl grid place-items-center bg-primary-soft text-primary shrink-0">
                  {s.icon}
                </div>
                <div className="pt-0.5 pr-12">
                  <div className="font-display text-[20px] sm:text-[22px] font-semibold text-ink tracking-tight">{s.title}</div>
                  <p className="text-ink-soft text-[14px] sm:text-[15px] mt-1.5 leading-[1.55]">{s.body}</p>
                </div>
              </div>
              {i < SOLUTION_STEPS.length - 1 && (
                <div className="absolute -bottom-3 left-9 sm:left-10 z-10">
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#1F4D3A" strokeWidth="2" strokeLinecap="round">
                    <path d="M12 4v16M6 14l6 6 6-6" />
                  </svg>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════
   SECTION 6 — USE CASES GRID
═══════════════════════════════════════════════════════ */
const USE_CASE_CARDS = [
  { label: 'Conferences',             icon: <Mic size={18} strokeWidth={1.8} />,          title: 'Conference attendees and speakers',              body: 'Every speaker, sponsor, and attendee gets their own branded variant of your event card.',                  image: '/usecase-conferences.png' },
  { label: 'NGOs',                    icon: <Heart size={18} strokeWidth={1.8} />,         title: 'Awareness and fundraising campaigns',            body: "Your supporters announce they're backing your cause — branded to your campaign.",                         image: '/usecase-ngo.png' },
  { label: 'Political campaigns',     icon: <Flag size={18} strokeWidth={1.8} />,          title: 'Endorsement and rally cards',                   body: 'Volunteers, endorsers, and supporters generate cards that look professional and personal at once.',         image: '/usecase-political.png' },
  { label: 'Religious organizations', icon: <Sun size={18} strokeWidth={1.8} />,           title: 'Event registration and community drives',       body: 'Members announce attendance at your conference, fast, or fundraiser.',                                    image: '/usecase-religious.png' },
  { label: 'Brand activations',       icon: <ShoppingBag size={18} strokeWidth={1.8} />,  title: 'Product launches and store openings',           body: 'Your customers and partners share branded launch announcements that drive real reach.',                    image: '/usecase-brand.png' },
  { label: 'Educational institutions',icon: <GraduationCap size={18} strokeWidth={1.8} />,title: 'Graduations, alumni, and scholarship campaigns', body: 'Graduates, alumni, and scholarship recipients each get their own moment to share.',                        image: '/usecase-education.png' },
];

function UseCasesGrid() {
  return (
    <section id="use-cases" className="relative">
      <div className="mx-auto max-w-[1200px] px-5 lg:px-10 py-20 lg:py-28">
        <Reveal>
          <div className="max-w-[760px] mb-12 lg:mb-16">
            <div className="font-mono text-[11px] tracking-[0.22em] text-primary uppercase mb-5">Who it&apos;s for</div>
            <h2 className="font-display font-bold text-ink text-[34px] sm:text-[44px] lg:text-[52px] leading-[1.02] tracking-[-0.03em]">
              Built for the campaign you&apos;re running this quarter.
            </h2>
            <p className="mt-5 text-ink-soft text-[17px] lg:text-[18px] leading-[1.55] max-w-[640px]">
              Six campaign types we&apos;ve shipped cards for. Your audience, your brand, in their hands.
            </p>
          </div>
        </Reveal>

        <div className="grid sm:grid-cols-2 gap-4 lg:gap-5">
          {USE_CASE_CARDS.map((c, i) => (
            <Reveal key={i} delay={i * 90}>
            <article
              className="relative bg-surface border border-border rounded-2xl p-6 lg:p-7 flex gap-5 lg:gap-6 hover:border-primary/30 hover:shadow-lift transition-all group"
            >
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2.5 mb-4">
                  <span className="w-9 h-9 rounded-full bg-primary-soft text-primary grid place-items-center shrink-0">
                    {c.icon}
                  </span>
                  <span className="font-mono text-[10px] tracking-[0.2em] text-primary uppercase">{c.label}</span>
                </div>
                <h3 className="font-display font-semibold text-ink text-[19px] lg:text-[22px] leading-[1.15] tracking-[-0.02em]">
                  {c.title}
                </h3>
                <p className="text-ink-soft text-[14px] lg:text-[15px] mt-2.5 leading-[1.55]">{c.body}</p>
                <Link
                  href="/use-cases"
                  className="mt-5 inline-flex items-center gap-1.5 text-primary font-medium text-[13px] hover:gap-2.5 transition-all"
                >
                  See example <ArrowRight size={14} strokeWidth={2} />
                </Link>
              </div>
              {c.image && (
                <div className="shrink-0 self-center hidden sm:block">
                  <Image
                    src={c.image}
                    alt={c.title}
                    width={120}
                    height={152}
                    className="rounded-xl object-cover shadow-soft"
                  />
                </div>
              )}
            </article>
            </Reveal>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════
   SECTION 7 — HOW IT WORKS (landing summary)
═══════════════════════════════════════════════════════ */
const HOW_STEPS = [
  {
    n: '01',
    icon: <Upload size={20} strokeWidth={1.6} />,
    title: 'Upload your design',
    body: 'Drop in any design from Canva, Figma, Illustrator — any PNG or JPG works.',
    caption: 'Works at any aspect ratio.',
    image: '/how-step-1.png',
  },
  {
    n: '02',
    icon: <ScanLine size={20} strokeWidth={1.6} />,
    title: 'Mark editable zones',
    body: 'Click to add text fields, photo zones, dropdowns, and custom fields.',
    caption: 'Each zone is one tap to edit.',
    image: '/how-step-2.png',
  },
  {
    n: '03',
    icon: <Share2 size={20} strokeWidth={1.6} />,
    title: 'Share the link',
    body: 'Send one link via WhatsApp, email, or QR code. Attendees personalize and download in seconds.',
    caption: 'No app downloads. No accounts.',
    image: '/how-step-3.png',
  },
];

function HowItWorks() {
  return (
    <section id="how" className="relative">
      <DotGrid opacity={0.05} />
      <div className="relative mx-auto max-w-[1200px] px-5 lg:px-10 py-20 lg:py-28">

        {/* Header */}
        <div className="mb-14 lg:mb-16">
          <div className="font-mono text-[11px] tracking-[0.22em] text-primary uppercase mb-4">How it works</div>
          <h2 className="font-display font-bold text-ink text-[44px] sm:text-[56px] lg:text-[64px] leading-[1.0] tracking-[-0.035em]">
            Three steps.<br />
            About <span className="text-accent">ten minutes.</span>
          </h2>
        </div>

        {/* 3-column cards */}
        <div className="grid lg:grid-cols-3 gap-5">
          {HOW_STEPS.map((s) => (
            <div
              key={s.n}
              className="bg-surface border border-border rounded-3xl overflow-hidden flex flex-col shadow-soft hover:shadow-lift transition-shadow duration-300 relative"
              style={{ backgroundImage: 'radial-gradient(circle at 1px 1px, rgba(15,31,24,0.055) 1px, transparent 0)', backgroundSize: '20px 20px' }}
            >
              {/* Text content */}
              <div className="p-6">
                <div className="flex items-center justify-between mb-5">
                  <span
                    className="h-8 w-8 rounded-full border border-border grid place-items-center font-mono text-[12px] text-ink-soft"
                    style={{ background: '#FAF6EE' }}
                  >
                    {s.n}
                  </span>
                  <span className="text-ink/25">{s.icon}</span>
                </div>
                <h3 className="font-display font-bold text-ink text-[22px] lg:text-[24px] leading-tight tracking-[-0.02em]">
                  {s.title}
                </h3>
                <p className="mt-2 text-ink-soft text-[14px] leading-[1.6]">{s.body}</p>
                <div className="mt-4 flex items-center gap-2 font-mono text-[10px] tracking-[0.16em] uppercase text-muted">
                  <span className="w-5 h-px bg-muted/40" />
                  {s.caption}
                </div>
              </div>

              {/* Illustration — flush to card bottom */}
              <Image
                src={s.image}
                alt={s.title}
                width={540}
                height={400}
                className="w-full"
              />
            </div>
          ))}
        </div>

        <div className="mt-12 flex justify-center">
          <Link
            href="/signup"
            className="inline-flex items-center gap-2 px-6 py-3.5 rounded-full bg-primary text-cream font-medium hover:bg-primary-dark transition-colors"
          >
            Start free <ArrowRight size={16} strokeWidth={2} />
          </Link>
        </div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════
   SECTION 8 — FEATURES (dark band)
═══════════════════════════════════════════════════════ */
const FEATURES = [
  { label: 'VARIANTS',     icon: <Layers size={20} strokeWidth={1.8} />,     title: 'One event, multiple roles',        body: 'Attendees, speakers, sponsors — each gets their own card layout from a single design.' },
  { label: 'PHOTO CROP',   icon: <Crop size={20} strokeWidth={1.8} />,       title: 'Smart photo cropping',             body: 'Matches your zone shape — circle, square, hexagon, rounded — automatically.' },
  { label: 'LIVE PREVIEW', icon: <Eye size={20} strokeWidth={1.8} />,        title: 'What they see is what they get',   body: 'Attendees see their card update as they type. No surprises at download.' },
  { label: 'SHARE BUILT-IN',icon: <Share2 size={20} strokeWidth={1.8} />,   title: 'One tap to every platform',        body: 'Instagram Stories, WhatsApp Status, X, Facebook — with caption suggestions.' },
  { label: 'AFRICA-FIRST', icon: <Globe size={20} strokeWidth={1.8} />,      title: 'Built for how Africa scrolls',     body: 'Low-bandwidth networks, mobile-first phones, WhatsApp-first sharing.' },
  { label: 'NO ACCOUNTS',  icon: <UserX size={20} strokeWidth={1.8} />,      title: 'Attendees never sign up',          body: 'They tap the link, make their card, move on. No friction. No funnel.' },
];

function Features() {
  return (
    <section className="bg-primary text-cream relative overflow-hidden">
      <div aria-hidden className="absolute inset-0 opacity-[0.06]" style={{ backgroundImage: 'radial-gradient(circle at 1px 1px, #E8C57E 1px, transparent 0)', backgroundSize: '32px 32px' }} />
      <div className="relative mx-auto max-w-[1200px] px-5 lg:px-10 py-20 lg:py-28">
        <Reveal>
          <div className="max-w-[760px] mb-12 lg:mb-16">
            <div className="font-mono text-[11px] tracking-[0.22em] text-accent uppercase mb-5">What&apos;s inside</div>
            <h2 className="font-display font-bold text-cream text-[34px] sm:text-[44px] lg:text-[52px] leading-[1.02] tracking-[-0.03em]">
              Built like a serious tool. Used like a link.
            </h2>
          </div>
        </Reveal>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-px rounded-2xl overflow-hidden border" style={{ background: 'rgba(250,246,238,0.1)', borderColor: 'rgba(250,246,238,0.15)' }}>
          {FEATURES.map((f, i) => (
            <Reveal key={i} delay={i * 80}>
            <div className="bg-primary p-6 lg:p-7 hover:bg-primary-dark transition-colors h-full">
              <div className="flex items-center gap-3 mb-5">
                <span className="w-10 h-10 rounded-lg grid place-items-center border" style={{ background: 'rgba(250,246,238,0.1)', color: '#E8C57E', borderColor: 'rgba(250,246,238,0.15)' }}>
                  {f.icon}
                </span>
                <span className="font-mono text-[10px] tracking-[0.22em] uppercase" style={{ color: '#E8C57E' }}>{f.label}</span>
              </div>
              <h3 className="font-display font-semibold text-cream text-[20px] lg:text-[22px] tracking-[-0.02em] leading-[1.15]">{f.title}</h3>
              <p className="mt-2.5 text-[14px] lg:text-[15px] leading-[1.55]" style={{ color: 'rgba(250,246,238,0.7)' }}>{f.body}</p>
            </div>
            </Reveal>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════
   SECTION 9 — PRICING TEASER
═══════════════════════════════════════════════════════ */
const PRICE_TIERS = [
  { name: 'Free',   price: '$0',  period: '',       blurb: 'For small campaigns and trials',              features: ['1 event', 'Up to 50 cards', 'Karta watermark', 'Email support'],                                      cta: 'Start free',        href: '/signup',           primary: false },
  { name: 'Pro',    price: '$29', period: '/month', blurb: 'For most organizers',                         features: ['5 events', 'Unlimited cards', 'No watermark', '3 variants per event', 'Basic analytics'],             cta: 'Start Pro trial',   href: '/signup?plan=pro',  primary: true,  badge: 'Most popular' },
  { name: 'Studio', price: '$99', period: '/month', blurb: 'For agencies and large campaigns',            features: ['Unlimited events', 'Unlimited cards', 'Unlimited variants', 'Brand kit', 'Team accounts', 'Priority support'], cta: 'Start Studio', href: '/signup?plan=studio', primary: false },
];

function PricingTeaser() {
  return (
    <section id="pricing" className="relative">
      <DotGrid opacity={0.05} />
      <div className="relative mx-auto max-w-[1200px] px-5 lg:px-10 py-20 lg:py-28">
        <Reveal>
          <div className="max-w-[760px] mb-12 lg:mb-16">
            <div className="font-mono text-[11px] tracking-[0.22em] text-primary uppercase mb-5">Pricing</div>
            <h2 className="font-display font-bold text-ink text-[34px] sm:text-[44px] lg:text-[52px] leading-[1.02] tracking-[-0.03em]">
              Pay only when you grow.
            </h2>
            <p className="mt-5 text-ink-soft text-[17px] lg:text-[18px] leading-[1.55]">
              Start free. Upgrade when your campaign goes bigger than 50 cards.
            </p>
          </div>
        </Reveal>

        <div className="grid lg:grid-cols-3 gap-5">
          {PRICE_TIERS.map((t, i) => (
            <Reveal key={t.name} delay={i * 100}>
            <div
              className={`relative rounded-3xl p-7 lg:p-8 flex flex-col h-full ${t.primary ? 'shadow-xl' : 'border border-border'}`}
              style={t.primary
                ? { background: '#1F4D3A', color: '#FAF6EE', boxShadow: '0 20px 60px rgba(31,77,58,0.25)' }
                : { background: '#FFFFFF' }
              }
            >
              {t.badge && (
                <div className="absolute -top-3 right-7 inline-flex items-center gap-1.5 font-mono text-[10px] tracking-[0.16em] uppercase bg-accent text-primary-dark px-2.5 py-1 rounded-full font-semibold">
                  {t.badge}
                </div>
              )}
              <div className={`font-display text-[14px] font-medium tracking-tight ${t.primary ? 'text-accent' : 'text-primary'}`}>
                {t.name}
              </div>
              <div className="mt-4 flex items-baseline gap-1.5">
                <span className={`font-display font-bold tracking-[-0.03em] text-[44px] leading-none ${t.primary ? 'text-cream' : 'text-ink'}`}>
                  {t.price}
                </span>
                {t.period && <span className={`text-[14px] ${t.primary ? 'text-cream/65' : 'text-muted'}`}>{t.period}</span>}
              </div>
              <div className={`mt-1.5 text-[14px] ${t.primary ? 'text-cream/75' : 'text-ink-soft'}`}>{t.blurb}</div>

              <ul className="mt-7 space-y-3 flex-1">
                {t.features.map(f => (
                  <li key={f} className={`flex items-start gap-2.5 text-[14px] ${t.primary ? 'text-cream/90' : 'text-ink-soft'}`}>
                    <span className={t.primary ? 'text-accent' : 'text-primary'}>
                      <Check size={15} strokeWidth={2.5} />
                    </span>
                    {f}
                  </li>
                ))}
              </ul>

              <Link
                href={t.href}
                className={`mt-8 inline-flex items-center justify-center gap-2 px-5 py-3 rounded-full font-medium text-[14px] transition-colors ${
                  t.primary ? 'bg-accent text-primary-dark hover:bg-accent-dark' : 'bg-ink text-cream hover:bg-primary'
                }`}
              >
                {t.cta} <ArrowRight size={14} strokeWidth={2} />
              </Link>
            </div>
            </Reveal>
          ))}
        </div>

        <div className="mt-10 text-center">
          <Link
            href="/pricing"
            className="inline-flex items-center gap-1.5 text-primary font-medium text-[14px] hover:gap-2.5 transition-all"
          >
            See full pricing details <ArrowRight size={14} strokeWidth={2} />
          </Link>
        </div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════
   SECTION 10 — TESTIMONIAL
═══════════════════════════════════════════════════════ */

/* ═══════════════════════════════════════════════════════
   SECTION 11 — FAQ
═══════════════════════════════════════════════════════ */
const LANDING_FAQS: FAQItem[] = [
  { q: 'Do attendees need to sign up?', a: 'No. Attendees never create an account. They tap your link, fill in their name, upload a photo if your card has one, and download. The whole flow takes under 30 seconds.' },
  { q: 'What file formats can I upload as my design?', a: 'PNG and JPG. Export from Canva, Figma, Illustrator, or Photoshop. Karta works at any aspect ratio — portrait Instagram cards, landscape Twitter cards, square LinkedIn cards.' },
  { q: 'Can I have different cards for different roles?', a: 'Yes. Pro and Studio plans support variants — Attendee, Speaker, Sponsor, Volunteer. Each variant can have its own copy, badge, or layout, all generated from the same base design.' },
  { q: 'Can attendees crop their photos?', a: 'Yes. Karta auto-crops to your zone shape (circle, square, hexagon, rounded) and lets attendees pinch-zoom and reposition before downloading.' },
  { q: 'Where can attendees share their card?', a: 'Anywhere. The download button is followed by one-tap share buttons for Instagram Stories, WhatsApp Status, X, Facebook, and LinkedIn — each with a suggested caption you can pre-write.' },
  { q: 'How is Karta different from Canva templates?', a: 'Canva templates need every attendee to open Canva, learn the editor, find the right file, and re-save. Karta is one link — they tap, type, download, share. Most attendees finish in under a minute.' },
  { q: 'What languages does Karta support?', a: 'Editor UI ships in English, French, Arabic, and Swahili. The attendee form accepts any Unicode text — you can write your card prompts in any language.' },
  { q: 'Can I see analytics on who downloaded their card?', a: 'Pro and Studio plans include a dashboard with download count, share-platform breakdown, top sharers, and time-of-day patterns. No personal data is collected from attendees.' },
];

function FAQSection() {
  return (
    <section id="faq" className="relative">
      <DotGrid opacity={0.05} />
      <div className="relative mx-auto max-w-[920px] px-5 lg:px-10 py-20 lg:py-28">
        <div className="mb-10 lg:mb-14 text-center">
          <div className="font-mono text-[11px] tracking-[0.22em] text-primary uppercase mb-5">FAQ</div>
          <h2 className="font-display font-bold text-ink text-[34px] sm:text-[42px] lg:text-[48px] leading-[1.02] tracking-[-0.03em]">
            Questions we get every week.
          </h2>
        </div>
        <FAQAccordion items={LANDING_FAQS} defaultOpen={0} />
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════
   SECTION 12 — FINAL CTA
═══════════════════════════════════════════════════════ */
function FinalCTA() {
  return (
    <section className="relative overflow-hidden">
      <div aria-hidden className="absolute pointer-events-none" style={{ top: '-40%', left: '50%', transform: 'translateX(-50%)', width: 640, height: 640, borderRadius: '50%', background: 'radial-gradient(circle, rgba(232,197,126,0.22), transparent 65%)', filter: 'blur(40px)' }} />
      <DotGrid opacity={0.05} />
      <div className="relative mx-auto max-w-[920px] px-5 lg:px-10 py-24 lg:py-32 text-center">
        <h2 className="font-display font-bold text-ink text-[44px] sm:text-[58px] lg:text-[72px] leading-[0.98] tracking-[-0.035em]">
          Start your first campaign today.
        </h2>
        <p className="mt-6 text-ink-soft text-[18px] lg:text-[19px] leading-[1.55] max-w-[640px] mx-auto">
          Free for up to 50 cards. No credit card. Most users have their first card ready in under five minutes.
        </p>
        <div className="mt-9 flex flex-wrap items-center justify-center gap-3">
          <Link
            href="/signup"
            className="inline-flex items-center gap-2 px-7 py-4 rounded-full bg-primary text-cream font-medium text-[16px] hover:bg-primary-dark transition-colors"
          >
            Start free <ArrowRight size={17} strokeWidth={2} />
          </Link>
          <Link
            href="#use-cases"
            className="inline-flex items-center gap-2 text-ink underline decoration-ink/30 underline-offset-4 hover:decoration-primary hover:text-primary transition-colors text-[15px]"
          >
            See use cases <ArrowRight size={14} strokeWidth={2} />
          </Link>
        </div>
      </div>
    </section>
  );
}

/* ═══════════════════════════════════════════════════════
   PAGE ASSEMBLY
═══════════════════════════════════════════════════════ */
export default async function LandingPage() {
  return (
    <>
      <Hero />
      <SocialProof />
      <StatsBar />
      <Reveal><Problem /></Reveal>
      <Reveal><Solution /></Reveal>
      <UseCasesGrid />
      <Reveal><HowItWorks /></Reveal>
      <Features />
      <PricingTeaser />
      <Reveal><Testimonials /></Reveal>
      <Reveal><FAQSection /></Reveal>
      <Reveal><FinalCTA /></Reveal>
    </>
  );
}
