/**
 * scripts/seed-cms-pages.ts
 *
 * Seeds all 10 marketing pages into the CMS.
 * Safe to run multiple times — uses upsert on slug.
 *
 * Usage:
 *   pnpm tsx scripts/seed-cms-pages.ts
 */

import { createClient } from '@supabase/supabase-js';
import type { Database } from '../types/database';
import type {
  BlockType,
  BlockContent,
  HeroContent,
  LogoStripContent,
  FeaturesGridContent,
  StepsGridContent,
  UseCasesGridContent,
  FaqAccordionContent,
  TestimonialContent,
  CtaContent,
  PricingCardsContent,
  ComparisonTableContent,
  SectionHeaderContent,
  TabInterfaceContent,
  TeamGridContent,
  PressSectionContent,
  ContactChannelsContent,
  CategoryGridContent,
  ProgramCardsContent,
  ProseSectionsContent,
} from '../lib/cms/types';
import type { Json } from '../types/database';

const supabase = createClient<Database>(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
);

// ── Helpers ───────────────────────────────────────────────────────────────────

async function upsertPage(slug: string, title: string) {
  const { data: existing } = await supabase
    .from('cms_pages')
    .select('id')
    .eq('slug', slug)
    .single();

  if (existing) {
    console.log(`  ↩  Page exists: ${slug} (${existing.id})`);
    return existing.id as string;
  }

  const { data, error } = await supabase
    .from('cms_pages')
    .insert({ slug, title, status: 'published', seo: {} as Json })
    .select('id')
    .single();

  if (error) throw new Error(`Failed to create page ${slug}: ${error.message}`);
  console.log(`  ✓  Created page: ${slug} (${data.id})`);
  return data.id as string;
}

async function setBlocks(
  pageId: string,
  blocks: Array<{ type: BlockType; content: BlockContent }>,
) {
  // Delete existing blocks for page
  await supabase.from('cms_blocks').delete().eq('page_id', pageId);

  if (blocks.length === 0) return;

  const rows = blocks.map((b, i) => ({
    page_id: pageId,
    type: b.type,
    content: b.content as unknown as Json,
    position: i,
  }));

  const { error } = await supabase.from('cms_blocks').insert(rows);
  if (error) throw new Error(`Failed to insert blocks: ${error.message}`);
  console.log(`     → ${blocks.length} blocks`);
}

// ── Page definitions ──────────────────────────────────────────────────────────

async function seedHome() {
  const id = await upsertPage('home', 'Landing Page');

  const hero: HeroContent = {
    eyebrow: 'Built for campaigns worth remembering',
    headline: 'Make every person proud to be there.',
    headlineAccent: 'proud to be there.',
    subheadline: 'One design. Every attendee gets a personalized card that feels made just for them — ready to share in 30 seconds.',
    imageUrl: '/hero.png',
    imageAlt: 'Three personalized event cards generated by Eventera',
    layout: 'split',
    buttons: [
      { label: 'Start free', href: '/signup', variant: 'primary' },
      { label: 'See how it works', href: '/how-it-works', variant: 'outline' },
    ],
    trustBadges: ['Free for up to 50 cards', '14-day free trial on Pro', 'Cancel anytime'],
  };

  const logoStrip: LogoStripContent = {
    label: 'Used for campaigns by',
    logos: [
      { name: 'AU', logo_url: undefined },
      { name: 'UNDP', logo_url: undefined },
      { name: 'MTN', logo_url: undefined },
      { name: 'GIZ', logo_url: undefined },
      { name: 'PSK', logo_url: undefined },
      { name: 'AFD', logo_url: undefined },
    ],
  };

  const features: FeaturesGridContent = {
    header: {
      eyebrow: "What's inside",
      headline: 'Built like a serious tool. Used like a link.',
      align: 'left',
    },
    background: 'dark',
    columns: 3,
    cards: [
      { label: 'VARIANTS',      title: 'One event, multiple roles',        body: 'Attendees, speakers, sponsors — each gets their own card layout from a single design.' },
      { label: 'PHOTO CROP',    title: 'Smart photo cropping',             body: 'Matches your zone shape — circle, square, hexagon, rounded — automatically.' },
      { label: 'LIVE PREVIEW',  title: 'What they see is what they get',   body: 'Attendees see their card update as they type. No surprises at download.' },
      { label: 'SHARE BUILT-IN',title: 'One tap to every platform',        body: 'Instagram Stories, WhatsApp Status, X, Facebook — with caption suggestions.' },
      { label: 'AFRICA-FIRST',  title: 'Built for how Africa scrolls',     body: 'Low-bandwidth networks, mobile-first phones, WhatsApp-first sharing.' },
      { label: 'NO ACCOUNTS',   title: 'Attendees never sign up',          body: 'They tap the link, make their card, move on. No friction. No funnel.' },
    ],
  };

  const steps: StepsGridContent = {
    header: {
      eyebrow: 'How it works',
      headline: 'Three steps. About ten minutes.',
      align: 'left',
    },
    layout: 'horizontal',
    steps: [
      { step: 1, icon: '↑', title: 'Upload your design', body: 'Drop in any design from Canva, Figma, Illustrator — any PNG or JPG works.', duration: 'Works at any aspect ratio.' },
      { step: 2, icon: '⊡', title: 'Mark editable zones', body: 'Click to add text fields, photo zones, dropdowns, and custom fields.', duration: 'Each zone is one tap to edit.' },
      { step: 3, icon: '↗', title: 'Share the link', body: 'Send one link via WhatsApp, email, or QR code. Attendees personalize and download in seconds.', duration: 'No app downloads. No accounts.' },
    ],
  };

  const useCases: UseCasesGridContent = {
    header: {
      eyebrow: "Who it's for",
      headline: "Built for the campaign you're running this quarter.",
      subtext: "Six campaign types we've shipped cards for. Your audience, your brand, in their hands.",
      align: 'left',
    },
    columns: 2,
    cases: [
      { id: 'conferences', label: 'Conferences', icon: '🎤', title: 'Conference attendees and speakers', body: 'Every speaker, sponsor, and attendee gets their own branded variant of your event card.', href: '/use-cases' },
      { id: 'ngos', label: 'NGOs', icon: '❤️', title: 'Awareness and fundraising campaigns', body: "Your supporters announce they're backing your cause — branded to your campaign.", href: '/use-cases' },
      { id: 'political', label: 'Political campaigns', icon: '🚩', title: 'Endorsement and rally cards', body: 'Volunteers, endorsers, and supporters generate cards that look professional and personal at once.', href: '/use-cases' },
      { id: 'religious', label: 'Religious organizations', icon: '☀️', title: 'Event registration and community drives', body: 'Members announce attendance at your conference, fast, or fundraiser.', href: '/use-cases' },
      { id: 'brand', label: 'Brand activations', icon: '🛍️', title: 'Product launches and store openings', body: 'Your customers and partners share branded launch announcements that drive real reach.', href: '/use-cases' },
      { id: 'education', label: 'Educational institutions', icon: '🎓', title: 'Graduations, alumni, and scholarship campaigns', body: 'Graduates, alumni, and scholarship recipients each get their own moment to share.', href: '/use-cases' },
    ],
  };

  const pricing: PricingCardsContent = {
    header: {
      eyebrow: 'Pricing',
      headline: 'Pay only when you grow.',
      subtext: 'Start free. Upgrade when your campaign goes bigger than 50 cards.',
      align: 'left',
    },
    teaser: true,
    plans: [
      { id: 'free', name: 'Free', headline: '', price: '$0', period: '', blurb: 'For small campaigns and trials', ctaLabel: 'Start free', ctaHref: '/signup', features: [{ text: '1 event', included: true }, { text: 'Up to 50 cards', included: true }, { text: 'Eventera watermark', included: true }, { text: 'Email support', included: true }] },
      { id: 'pro', name: 'Pro', headline: '', price: '$29', period: '/month', blurb: 'For most organizers', ctaLabel: 'Start Pro trial', ctaHref: '/signup?plan=pro', highlighted: true, badge: 'Most popular', features: [{ text: '5 events', included: true }, { text: 'Unlimited cards', included: true }, { text: 'No watermark', included: true }, { text: '3 variants per event', included: true }, { text: 'Basic analytics', included: true }] },
      { id: 'studio', name: 'Studio', headline: '', price: '$99', period: '/month', blurb: 'For agencies and large campaigns', ctaLabel: 'Start Studio', ctaHref: '/signup?plan=studio', features: [{ text: 'Unlimited events', included: true }, { text: 'Unlimited cards', included: true }, { text: 'Unlimited variants', included: true }, { text: 'Brand kit', included: true }, { text: 'Team accounts', included: true }, { text: 'Priority support', included: true }] },
    ],
  };

  const testimonial: TestimonialContent = {
    quote: 'Eventera let us turn 600 attendees into 600 brand ambassadors. The reach was far beyond what we expected — and the visual identity stayed locked the whole way.',
    authorName: 'Amara Yusuf',
    authorRole: 'Comms Lead · Pan-African Climate Summit',
  };

  const faq: FaqAccordionContent = {
    header: { eyebrow: 'FAQ', headline: 'Questions we get every week.', align: 'center' },
    defaultOpen: 0,
    items: [
      { question: 'Do attendees need to sign up?', answer: 'No. Attendees never create an account. They tap your link, fill in their name, upload a photo if your card has one, and download. The whole flow takes under 30 seconds.' },
      { question: 'What file formats can I upload as my design?', answer: 'PNG and JPG. Export from Canva, Figma, Illustrator, or Photoshop. Eventera works at any aspect ratio — portrait Instagram cards, landscape Twitter cards, square LinkedIn cards.' },
      { question: 'Can I have different cards for different roles?', answer: 'Yes. Pro and Studio plans support variants — Attendee, Speaker, Sponsor, Volunteer. Each variant can have its own copy, badge, or layout, all generated from the same base design.' },
      { question: 'Can attendees crop their photos?', answer: 'Yes. Eventera auto-crops to your zone shape (circle, square, hexagon, rounded) and lets attendees pinch-zoom and reposition before downloading.' },
      { question: 'Where can attendees share their card?', answer: 'Anywhere. The download button is followed by one-tap share buttons for Instagram Stories, WhatsApp Status, X, Facebook, and LinkedIn — each with a suggested caption you can pre-write.' },
      { question: 'How is Eventera different from Canva templates?', answer: "Canva templates need every attendee to open Canva, learn the editor, find the right file, and re-save. Eventera is one link — they tap, type, download, share. Most attendees finish in under a minute." },
      { question: 'What languages does Eventera support?', answer: 'Editor UI ships in English, French, Arabic, and Swahili. The attendee form accepts any Unicode text — you can write your card prompts in any language.' },
      { question: 'Can I see analytics on who downloaded their card?', answer: 'Pro and Studio plans include a dashboard with download count, share-platform breakdown, top sharers, and time-of-day patterns. No personal data is collected from attendees.' },
    ],
  };

  const cta: CtaContent = {
    headline: 'Start your first campaign today.',
    subtext: 'Free for up to 50 cards. No credit card. Most users have their first card ready in under five minutes.',
    buttons: [
      { label: 'Start free', href: '/signup', variant: 'primary' },
      { label: 'See a live example', href: '/use-cases', variant: 'link' },
    ],
    background: 'default',
  };

  await setBlocks(id, [
    { type: 'hero', content: hero },
    { type: 'logoStrip', content: logoStrip },
    { type: 'featuresGrid', content: features },
    { type: 'stepsGrid', content: steps },
    { type: 'useCasesGrid', content: useCases },
    { type: 'pricingCards', content: pricing },
    { type: 'testimonial', content: testimonial },
    { type: 'faqAccordion', content: faq },
    { type: 'cta', content: cta },
  ]);
}

async function seedPricing() {
  const id = await upsertPage('pricing', 'Pricing');

  const header: SectionHeaderContent = {
    eyebrow: 'Pricing',
    headline: 'Pay only when you grow.',
    subtext: 'Start free. No credit card required. Upgrade anytime.',
    align: 'left',
  };

  const plans: PricingCardsContent = {
    header,
    showToggle: true,
    trialBanner: '14-day free trial on Pro. No credit card required.',
    trustItems: ['Cancel anytime', 'No setup fees', 'Priority support on Studio'],
    plans: [
      { id: 'free', name: 'Free', headline: '', price: '$0', period: '', blurb: 'For small campaigns and trials', ctaLabel: 'Start free', ctaHref: '/signup', features: [{ text: '1 active event', included: true }, { text: 'Up to 50 cards / event', included: true }, { text: '1 variant per event', included: true }, { text: 'Eventera watermark on cards', included: true }, { text: 'Email support', included: true }] },
      { id: 'pro', name: 'Pro', headline: '', price: '$29', period: '/month', blurb: 'For most organizers', ctaLabel: 'Start 14-day trial', ctaHref: '/signup?plan=pro', highlighted: true, badge: 'Most popular', features: [{ text: '5 active events', included: true }, { text: 'Unlimited cards', included: true }, { text: 'No watermark', included: true }, { text: '3 variants per event', included: true }, { text: 'Basic analytics', included: true }, { text: 'Priority email support', included: true }] },
      { id: 'studio', name: 'Studio', headline: '', price: '$99', period: '/month', blurb: 'For agencies and large campaigns', ctaLabel: 'Start Studio trial', ctaHref: '/signup?plan=studio', features: [{ text: 'Unlimited events', included: true }, { text: 'Unlimited cards', included: true }, { text: 'Unlimited variants', included: true }, { text: 'Brand kit', included: true }, { text: 'Team accounts (coming)', included: true }, { text: 'Priority support + SLA', included: true }] },
    ],
  };

  const comparison: ComparisonTableContent = {
    header: { eyebrow: 'Compare plans', headline: 'Everything side by side.', align: 'left' },
    groups: [
      {
        label: 'Events & Cards',
        rows: [
          { feature: 'Active events', free: '1', pro: '5', studio: 'Unlimited' },
          { feature: 'Cards per event', free: '50', pro: 'Unlimited', studio: 'Unlimited' },
          { feature: 'Variants per event', free: '1', pro: '3', studio: 'Unlimited' },
          { feature: 'Watermark on cards', free: true, pro: false, studio: false },
        ],
      },
      {
        label: 'Features',
        rows: [
          { feature: 'Photo zones (circle, square, etc.)', free: true, pro: true, studio: true },
          { feature: 'QR code for event link', free: true, pro: true, studio: true },
          { feature: 'Custom slug', free: false, pro: true, studio: true },
          { feature: 'Brand kit', free: false, pro: false, studio: true },
          { feature: 'Team accounts', free: false, pro: false, studio: 'Coming' },
          { feature: 'CSV export', free: false, pro: true, studio: true },
          { feature: 'Webhook events', free: false, pro: false, studio: true },
        ],
      },
      {
        label: 'Analytics',
        rows: [
          { feature: 'Download count', free: true, pro: true, studio: true },
          { feature: 'Share platform breakdown', free: false, pro: true, studio: true },
          { feature: 'Top sharers', free: false, pro: true, studio: true },
          { feature: 'Time-of-day patterns', free: false, pro: false, studio: true },
        ],
      },
      {
        label: 'Support',
        rows: [
          { feature: 'Email support', free: true, pro: true, studio: true },
          { feature: 'Priority support', free: false, pro: true, studio: true },
          { feature: 'SLA', free: false, pro: false, studio: true },
        ],
      },
    ],
  };

  const faq: FaqAccordionContent = {
    header: { eyebrow: 'FAQ', headline: 'Pricing questions.', align: 'center' },
    items: [
      { question: 'What counts as an "active event"?', answer: 'Any event with status Published or Draft. Archived events do not count toward your limit.' },
      { question: 'Can I upgrade or downgrade mid-month?', answer: 'Yes. When you upgrade, you get immediate access to the new plan. When you downgrade, the change takes effect at the start of your next billing cycle.' },
      { question: 'Is there a free trial?', answer: 'Yes. Pro and Studio plans include a 14-day free trial. No credit card required to start.' },
      { question: 'What happens when my free tier event hits 50 cards?', answer: 'New card generation is paused. You can upgrade to Pro at any time to remove the limit retroactively — existing cards are not deleted.' },
      { question: 'Do you offer discounts for NGOs or educational institutions?', answer: 'Yes. Email hello@eventera.so with your organization name and use case. We evaluate each case individually.' },
    ],
  };

  const cta: CtaContent = {
    headline: 'Start free today.',
    subtext: 'No credit card. No lock-in. Most campaigns are live in under 10 minutes.',
    buttons: [
      { label: 'Start for free', href: '/signup', variant: 'primary' },
      { label: 'Talk to us', href: '/contact', variant: 'outline' },
    ],
    background: 'default',
  };

  await setBlocks(id, [
    { type: 'pricingCards', content: plans },
    { type: 'comparisonTable', content: comparison },
    { type: 'faqAccordion', content: faq },
    { type: 'cta', content: cta },
  ]);
}

async function seedHowItWorks() {
  const id = await upsertPage('how-it-works', 'How It Works');

  const header: SectionHeaderContent = {
    eyebrow: 'How it works',
    headline: 'From design to 10,000 personalized cards.',
    subtext: 'Four steps. About ten minutes of setup. Then it runs itself.',
    align: 'center',
  };

  const steps: StepsGridContent = {
    layout: 'alternating',
    steps: [
      { step: 1, short: 'Upload your design', duration: '~2 min', title: 'Drop in any design. Eventera handles the rest.', body: 'Export from Canva, Figma, Illustrator, Photoshop — anywhere. PNG or JPG, any aspect ratio. We auto-detect the canvas size and place it on the editor at the right scale.', bullets: ['PNG / JPG · up to 20 MB', 'Any aspect ratio · portrait, square, landscape', 'Auto-detected safe area for typography', 'Multiple designs per event (Speaker variant, Sponsor variant)'] },
      { step: 2, short: 'Mark editable zones', duration: '~3 min', title: 'Click to mark where attendees personalize.', body: 'Drop text fields, photo zones, and dropdowns directly on the canvas. Each zone has its own typography, max length, photo shape, and validation. Need different roles? Add variants.', bullets: ['Text · name, role, organization, anything', 'Photo · circle, square, hexagon, rounded — auto crop', 'Dropdown · pick from list (department, country, ticket tier)', 'Variants per event · up to unlimited on Studio'] },
      { step: 3, short: 'Publish your link', duration: '~30 sec', title: 'One link. WhatsApp, email, QR. No accounts.', body: "Eventera generates a short URL and a QR code for your campaign. Share it however your audience already shares — WhatsApp groups, email blasts, printed flyers, event signage. Attendees never sign up.", bullets: ['Short URL · eventera.so/your-slug', 'QR code · downloadable PNG and SVG', 'Embed code · drop into any website', 'No attendee account, no app download'] },
      { step: 4, short: 'Watch your audience share', duration: 'Live', title: 'Track reach as your campaign goes off.', body: "Real-time analytics show how many cards have been generated, where they're being shared, and which variants are performing. Export to CSV or pipe to your data tool via webhook.", bullets: ['Live counter · cards generated, per variant', 'Share platform breakdown · WhatsApp, IG, X, LinkedIn', 'Top sharers · spot your loudest advocates', 'CSV export · or webhook events to your stack'] },
    ],
  };

  const cta: CtaContent = {
    headline: 'Ready to run your campaign?',
    subtext: 'Start free. Your first card can be live in under 10 minutes.',
    buttons: [{ label: 'Start free', href: '/signup', variant: 'primary' }],
    background: 'default',
  };

  await setBlocks(id, [
    { type: 'sectionHeader', content: header },
    { type: 'stepsGrid', content: steps },
    { type: 'cta', content: cta },
  ]);
}

async function seedUseCases() {
  const id = await upsertPage('use-cases', 'Use Cases');

  const header: SectionHeaderContent = {
    eyebrow: "Who it's for",
    headline: 'Every campaign type, one tool.',
    subtext: "Whether you're running a conference, a fundraiser, or a graduation — Eventera generates the personalized cards your attendees actually share.",
    align: 'center',
  };

  const grid: UseCasesGridContent = {
    columns: 2,
    cases: [
      { id: 'conferences', label: 'Conferences', icon: '🎤', title: 'Conference attendees and speakers', body: 'Every speaker, sponsor, and attendee gets their own branded variant of your event card. Works at any scale — from 50-person meetups to 10,000-person summits.', href: '/use-cases#conferences' },
      { id: 'ngos', label: 'NGOs & Nonprofits', icon: '❤️', title: 'Awareness and fundraising campaigns', body: "Your supporters announce they're backing your cause — branded to your campaign. Peer-to-peer sharing at its most powerful.", href: '/use-cases#ngos' },
      { id: 'political', label: 'Political campaigns', icon: '🚩', title: 'Endorsement and rally cards', body: 'Volunteers, endorsers, and supporters generate cards that look professional and personal at once. Your message, their face, your brand.', href: '/use-cases#political' },
      { id: 'religious', label: 'Religious organizations', icon: '☀️', title: 'Event registration and community drives', body: 'Members announce attendance at your conference, fast, or fundraiser. No tech skills required — it works on any phone.', href: '/use-cases#religious' },
      { id: 'brand', label: 'Brand activations', icon: '🛍️', title: 'Product launches and store openings', body: 'Your customers and partners share branded launch announcements that drive real reach. Every post looks like it came from your creative team.', href: '/use-cases#brand' },
      { id: 'education', label: 'Educational institutions', icon: '🎓', title: 'Graduations, alumni, and scholarship campaigns', body: 'Graduates, alumni, and scholarship recipients each get their own moment to share. The institution looks great. The individual feels celebrated.', href: '/use-cases#education' },
    ],
  };

  const tabs: TabInterfaceContent = {
    tabs: [
      { id: 'conferences', label: 'Conferences', icon: '🎤', headline: 'Make every speaker feel like a headliner.', blurb: 'Conference cards are the most-shared content from any event. Every speaker, sponsor, and attendee gets a variant that matches their role.', problems: [{ text: 'Off-brand attendee posts on social' }, { text: 'Designer spending nights making individual cards' }, { text: 'Low social reach because sharing is too hard' }], examples: [{ title: 'Speaker card', role: 'Confirmed speaker' }, { title: 'Sponsor card', role: 'Gold sponsor' }, { title: 'Attendee card', role: 'General attendee' }] },
      { id: 'ngos', label: 'NGOs', icon: '❤️', headline: 'Turn every supporter into a campaign poster.', blurb: "Awareness campaigns live or die on peer sharing. When supporters can generate their own branded card in 30 seconds, your message travels further than any ad budget.", problems: [{ text: 'Supporters share generic campaign graphics' }, { text: 'No easy way to personalize at scale' }, { text: 'Reach stays inside your existing audience' }], examples: [{ title: 'Supporter card', role: 'Campaign backer' }, { title: 'Volunteer card', role: 'On-the-ground' }, { title: 'Donor card', role: 'Fundraising tier' }] },
      { id: 'political', label: 'Political', icon: '🚩', headline: 'Professional endorsements from every volunteer.', blurb: 'Political campaigns need brand consistency at huge scale. Eventera gives every volunteer, endorser, and rally attendee a personalized card that looks like it was designed by your creative team.', problems: [{ text: 'Volunteers using unauthorized graphics' }, { text: 'Inconsistent messaging across supporter posts' }, { text: 'Rally attendance barely visible online' }], examples: [{ title: 'Endorsement card', role: 'Public endorser' }, { title: 'Volunteer card', role: 'Campaign volunteer' }, { title: 'Rally card', role: 'Event attendee' }] },
    ],
  };

  const cta: CtaContent = {
    headline: 'Start your campaign today.',
    subtext: 'Free for up to 50 cards. Most campaigns are live in under 10 minutes.',
    buttons: [{ label: 'Start free', href: '/signup', variant: 'primary' }, { label: 'See pricing', href: '/pricing', variant: 'outline' }],
    background: 'default',
  };

  await setBlocks(id, [
    { type: 'sectionHeader', content: header },
    { type: 'useCasesGrid', content: grid },
    { type: 'tabInterface', content: tabs },
    { type: 'cta', content: cta },
  ]);
}

async function seedAbout() {
  const id = await upsertPage('about', 'About');

  const hero: HeroContent = {
    eyebrow: 'About Eventera',
    headline: 'Built in Djibouti.',
    headlineAccent: 'For the world.',
    subheadline: "Eventera is the tool we wished existed when we ran campaigns ourselves. Built Africa-first — but the problem is global.",
    layout: 'split',
    statsStrip: [
      { value: '2024', label: 'Founded' },
      { value: '8', label: 'Countries served' },
      { value: '1', label: 'Coffee per feature' },
    ],
    buttons: [],
  };

  const team: TeamGridContent = {
    header: {
      eyebrow: 'Team',
      headline: 'A small team. A clear remit.',
      subtext: "Building Eventera alone for now. If you've worked on African campaigns and want to build the tool you wish existed — let's talk.",
      align: 'left',
    },
    ctaButton: { label: 'Get in touch', href: 'mailto:hello@eventera.so', variant: 'primary' },
    members: [
      { name: 'Abdalla', role: 'Founder', location: 'Djibouti' },
      { name: 'Open role', role: 'Founding Engineer', location: 'Remote · Africa', is_open_role: true, apply_href: 'mailto:hello@eventera.so' },
      { name: 'Open role', role: 'Designer', location: 'Remote · Africa', is_open_role: true, apply_href: 'mailto:hello@eventera.so' },
      { name: 'Open role', role: 'Community', location: 'Remote · Africa', is_open_role: true, apply_href: 'mailto:hello@eventera.so' },
    ],
  };

  const features: FeaturesGridContent = {
    header: {
      eyebrow: 'What Eventera stands for',
      headline: "Three things we'll never water down.",
      align: 'left',
    },
    background: 'dark',
    columns: 3,
    cards: [
      { label: 'Design',  title: 'African-modern, not African-themed.', body: 'We design for how Africa actually scrolls — fast feeds, WhatsApp Status, mobile-first phones. Not a stereotyped version of it.' },
      { label: 'Product', title: 'The link is the product.',             body: 'No accounts, no apps, no funnels for the attendees. One tap is the bar. If we ever raise that bar by a millimeter, something has gone wrong.' },
      { label: 'Brand',   title: 'Consistency at scale.',                body: "Your design system survives 10,000 supporters posting from 40 phones. That's the whole reason we built this." },
    ],
  };

  const press: PressSectionContent = {
    label: 'Talked about in',
    mentions: [
      { publication: 'Disrupt Africa', date: 'MAR 2026', quote: "A small Djibouti-based team is quietly fixing the most common comms failure on the continent's event circuit." },
      { publication: 'TechCabal',      date: 'APR 2026', quote: "Eventera's WhatsApp-first share flow is exactly the kind of design African startups should be exporting." },
      { publication: 'Rest of World',  date: 'MAY 2026', quote: 'Built for low-bandwidth, mobile-first audiences — and increasingly used by global brands running campaigns there.' },
    ],
  };

  const cta: CtaContent = {
    headline: 'Want to talk?',
    subtext: 'We read every email. Press, partnerships, weird ideas, hard problems. Especially the hard problems.',
    buttons: [
      { label: 'hello@eventera.so', href: 'mailto:hello@eventera.so', variant: 'primary' },
      { label: 'Try the product first', href: '/signup', variant: 'outline' },
    ],
    background: 'default',
  };

  await setBlocks(id, [
    { type: 'hero', content: hero },
    { type: 'featuresGrid', content: features },
    { type: 'teamGrid', content: team },
    { type: 'pressSection', content: press },
    { type: 'cta', content: cta },
  ]);
}

async function seedContact() {
  const id = await upsertPage('contact', 'Contact');

  const channels: ContactChannelsContent = {
    header: {
      eyebrow: 'Contact',
      headline: 'Get in touch.',
      subtext: 'We reply within 24 hours, usually faster.',
      align: 'left',
    },
    channels: [
      { icon: 'mail', label: 'Email', href: 'mailto:hello@eventera.so', description: 'For general questions, feedback, and support.' },
      { icon: 'whatsapp', label: 'WhatsApp', href: '#', description: 'For quick questions and demo requests.' },
    ],
    reasons: [
      "You want to set up a Pro or Studio account",
      "You have a specific event coming up and want to make sure Eventera can handle it",
      "Something broke and you need help urgently",
      "You have feedback on the product — we read all of it",
      "You're an NGO or educational organization and want to discuss pricing",
      "You want to collaborate (design, engineering, growth)",
    ],
  };

  await setBlocks(id, [{ type: 'contactChannels', content: channels }]);
}

async function seedHelp() {
  const id = await upsertPage('help', 'Help Center');

  const header: SectionHeaderContent = {
    eyebrow: 'Help center',
    headline: 'How can we help?',
    subtext: 'Browse categories or search for answers.',
    align: 'center',
  };

  const categories = {
    header: { eyebrow: 'Browse by topic', headline: '', align: 'left' as const },
    categories: [
      { icon: '🚀', title: 'Getting started', description: 'Create your first event and publish your first card.', articles: [{ title: 'Create your first event', href: '/help/getting-started' }, { title: 'Upload a design', href: '/help/upload-design' }, { title: 'Mark editable zones', href: '/help/editor-zones' }, { title: 'Publish and share your link', href: '/help/publish' }] },
      { icon: '🎨', title: 'Design & Editor', description: 'Zone types, fonts, photo shapes, and layout tools.', articles: [{ title: 'Text zone options', href: '/help/text-zones' }, { title: 'Photo zone shapes', href: '/help/photo-zones' }, { title: 'Using variants', href: '/help/variants' }, { title: 'Supported design formats', href: '/help/formats' }] },
      { icon: '📊', title: 'Analytics', description: 'Track downloads, shares, and campaign performance.', articles: [{ title: 'Reading your analytics dashboard', href: '/help/analytics' }, { title: 'Export to CSV', href: '/help/csv-export' }, { title: 'Webhook events', href: '/help/webhooks' }] },
      { icon: '💳', title: 'Billing', description: 'Plans, payments, and upgrades.', articles: [{ title: 'Compare plans', href: '/pricing' }, { title: 'Upgrade to Pro', href: '/settings/billing' }, { title: 'Cancel or pause a subscription', href: '/help/cancel' }, { title: 'NGO and education discounts', href: '/help/discounts' }] },
      { icon: '🔐', title: 'Account & Security', description: 'Profile, passwords, and team access.', articles: [{ title: 'Change your email', href: '/help/change-email' }, { title: 'Reset your password', href: '/forgot-password' }, { title: 'Delete your account', href: '/help/delete-account' }] },
      { icon: '🛠️', title: 'Troubleshooting', description: "Something not working? Start here.", articles: [{ title: 'Attendees can\'t open my link', href: '/help/link-not-working' }, { title: 'Card download is broken', href: '/help/download-broken' }, { title: 'Photo upload fails', href: '/help/photo-upload' }, { title: 'Contact support', href: '/contact' }] },
    ],
  };

  await setBlocks(id, [
    { type: 'sectionHeader', content: header },
    { type: 'categoryGrid', content: categories },
  ]);
}

async function seedPartners() {
  const id = await upsertPage('partners', 'Partners');

  const header: SectionHeaderContent = {
    eyebrow: 'Partners',
    headline: 'Build with Eventera.',
    subtext: "We're building partnership programs for agencies, event producers, and platforms that want to bring personalized card generation to their clients.",
    align: 'left',
  };

  const programs = {
    header: { eyebrow: 'Programs', headline: 'How we work together.', align: 'left' as const },
    programs: [
      { icon: '🤝', tag: 'Agency', title: 'Agency Partner', description: 'For creative agencies and event production companies that manage campaigns for multiple clients.', bullets: ['White-label option', 'Multi-client dashboard', 'Revenue share on referrals', 'Early access to new features', 'Dedicated account manager'] },
      { icon: '🔌', tag: 'Platform', title: 'Platform Integration', description: 'Integrate Eventera into your event management, CRM, or marketing platform via API.', bullets: ['Full REST API access', 'Webhook events', 'Custom domain support', 'SLA guarantee', 'Engineering support'] },
      { icon: '📢', tag: 'Referral', title: 'Referral Program', description: 'Refer clients and earn recurring commission for every plan they subscribe to.', bullets: ['20% recurring commission', 'Real-time dashboard', 'Minimum payout: $50', 'Monthly payouts via transfer', 'No cap on earnings'] },
    ],
  };

  const cta: CtaContent = {
    headline: 'Interested in partnering?',
    subtext: "Tell us about your use case and we'll figure out the best fit together.",
    buttons: [{ label: 'Apply to partner', href: 'mailto:partners@eventera.so', variant: 'primary' }],
    background: 'default',
  };

  await setBlocks(id, [
    { type: 'sectionHeader', content: header },
    { type: 'programCards', content: programs },
    { type: 'cta', content: cta },
  ]);
}

async function seedPrivacy() {
  const id = await upsertPage('privacy', 'Privacy Policy');

  const prose: ProseSectionsContent = {
    eyebrow: 'Legal',
    headline: 'Privacy Policy',
    updatedAt: 'May 2026',
    warningBanner: "Note: We'll review this with a lawyer before formal launch. What's below is our honest current practice, written in plain English.",
    sections: [
      { h2: 'What we collect', paragraphs: ['When you create an account: your email address, and your name (optional, if you add it to your profile).', 'When you create an event: the design image you upload (stored in Supabase cloud storage), the zone configuration you define (stored in our database), and your event name and settings.', 'When an attendee fills out your event card: the name, title, company, and any other text fields you defined; the photo they upload (if your design includes a photo zone); and the generated card image (the personalized PNG output).'] },
      { h2: 'How we use it', paragraphs: ['To provide the card generation service, to store your events and let you manage them, and to show you how many cards have been generated for each event.', 'We do not sell your data or attendee data to third parties. We do not use attendee data for marketing. We do not share your design files with anyone other than you.'] },
      { h2: 'Where data is stored', paragraphs: ["We use Supabase for our database and file storage. Files are stored in Supabase's cloud infrastructure. Your account data lives in a Supabase database. You can read Supabase's own privacy policy at supabase.com/privacy."] },
      { h2: 'Cookies', paragraphs: ['We use a session cookie to keep you logged in. We do not use tracking cookies or third-party advertising cookies. We do not run Google Analytics or Facebook Pixel.'] },
      { h2: 'Attendee data retention', paragraphs: ['Attendee names, photos, and generated cards are stored as long as the event exists in your account. When you delete an event, all associated attendee data and generated cards are deleted too.'] },
      { h2: 'Your rights', paragraphs: ['You can delete your account at any time. When you delete your account, all your events, design files, and associated attendee data are permanently removed. If you want to delete only specific events, you can do that from the dashboard.', 'If you are an attendee who submitted data through an Eventera event and want that data removed, email us at hello@eventera.so with the event name.'] },
      { h2: 'Contact', paragraphs: ['Privacy questions: hello@eventera.so. We\'re a small team and we reply to every message.'] },
    ],
  };

  await setBlocks(id, [{ type: 'proseSections', content: prose }]);
}

async function seedTerms() {
  const id = await upsertPage('terms', 'Terms of Service');

  const prose: ProseSectionsContent = {
    eyebrow: 'Legal',
    headline: 'Terms of Service',
    updatedAt: 'May 2026',
    warningBanner: "Note: We'll review this with a lawyer before formal launch. This is a plain-English summary of our current rules.",
    sections: [
      { h2: 'What Eventera is', paragraphs: ['Eventera is a tool that lets event organizers create personalized social share cards for their attendees. You upload a design, define which parts attendees can fill in, publish a link, and we handle the card generation.'] },
      { h2: 'Your account', paragraphs: ['You must be 18 or older to create an account. You are responsible for keeping your login credentials secure. You are responsible for everything that happens under your account.'] },
      { h2: 'What you can upload', paragraphs: ['You can upload designs that you own or have rights to use. Do not upload designs that infringe on someone else\'s copyright or trademark. Do not upload designs that contain illegal content, hate speech, or material that violates the rights of others.', 'We reserve the right to remove events and designs that violate these terms without notice.'] },
      { h2: 'Attendee data', paragraphs: ['Attendees who use your event link submit their data directly to your event. As the event creator, you are the data controller for that attendee information. You are responsible for informing your attendees about how their data is used.'] },
      { h2: 'Payments', paragraphs: ['Pro and Studio plans are billed monthly or annually via Stripe. Prices are in USD. We may change pricing with 30 days notice. Refunds are handled case by case — email hello@eventera.so.'] },
      { h2: 'Cancellation', paragraphs: ['You can cancel your plan at any time from your billing settings. Cancellation takes effect at the end of your current billing period. Your events and data remain accessible until then.'] },
      { h2: 'Limitation of liability', paragraphs: ['Eventera is provided "as is." We make no warranties about uptime or fitness for a particular purpose. Our liability is limited to what you paid us in the past 12 months.'] },
      { h2: 'Changes to these terms', paragraphs: ['We may update these terms. We\'ll notify you via email at least 14 days before major changes take effect. Continued use of Eventera after that date constitutes acceptance.'] },
      { h2: 'Contact', paragraphs: ['Legal questions: hello@eventera.so.'] },
    ],
  };

  await setBlocks(id, [{ type: 'proseSections', content: prose }]);
}

// ── Run ───────────────────────────────────────────────────────────────────────

async function main() {
  console.log('🌱 Seeding CMS pages…\n');

  const pages = [
    { name: 'Home (landing)',  fn: seedHome },
    { name: 'Pricing',        fn: seedPricing },
    { name: 'How It Works',   fn: seedHowItWorks },
    { name: 'Use Cases',      fn: seedUseCases },
    { name: 'About',          fn: seedAbout },
    { name: 'Contact',        fn: seedContact },
    { name: 'Help Center',    fn: seedHelp },
    { name: 'Partners',       fn: seedPartners },
    { name: 'Privacy Policy', fn: seedPrivacy },
    { name: 'Terms',          fn: seedTerms },
  ];

  for (const { name, fn } of pages) {
    console.log(`\n📄 ${name}`);
    await fn();
  }

  console.log('\n✅ Done. All pages seeded.\n');
}

main().catch((err) => {
  console.error('❌ Seed failed:', err.message);
  process.exit(1);
});
